### ISSUE TITLE
Feature: should.be.null ?

### ISSUE THREAD

**Issue by kruncher** [shouldjs/should.js#103]
Hi.

I realize that there is `should.not.exist` which checks to see whether a value is `null` or `undefined`; but it would be awesome if there were a way to test `null` and `undefined` explicitly.

For instance,

```javascript
should.be.null( foo );
should.not.be.null( foo );
should.be.undefined( foo );
should.not.be.undefined( foo );
```

Is there already a way to achieve this that I am not aware of?

Would this be something that could be added to should.js?

p.s.
Many thanks to all the developers who work on my favourite assertion library :)

**Comment by btd** [comment]
You can use:
```js
should(null).be.null();
should(undefined).be.undefined();
```

Example: https://tonicdev.com/56b9edb2a52a460c001d52df/56c6f8fa65a31b0d00a4195d

**Comment by kruncher** [comment]
@btd Awesome, thanks for the crazy fast response!! :D
