### ISSUE TITLE
Ability to provide argument 'description' to `.true()` and `.false()`

### ISSUE THREAD

**Issue by kruncher** [shouldjs/should.js#104]
Hi.

It would be great if the `.true()` and `.false()` operators allowed the `description` argument to be specified such that the following is possible:

```javascript
result.should.be.true("some detailed information about the failure");
```

It seems that this operator is just implemented using `.exactly` and as such the following offers identical behavior:

```javascript
result.should.be.exactly(true, "some detailed information about the failure");
```

Would it be possible to add this to should.js?

Many thanks!

**Comment by btd** [comment]
Yes, that is possible for sure. But actually i noticed you are going from this [SO question](http://stackoverflow.com/questions/36035872/how-to-provide-more-information-about-assertion-failure-with-should-js)
in your case i would suggest to make own assertion like:
```
should.Assertion.add('validForSchema', function(schemaFunc) {
  this.params = { message: 'to be valid for schema' };
  let result = schemaFunc(this.obj);
  if(!result) {
    this.params.message += `. Errors: ${schemaFunc.errors.map(err => should.format(err))}`;
  }
  result.should.be.true();
});
```
Now you can write more accurate assertions:
```
const makeValidator = require('is-my-json-valid');
const should = require('should');

let schema = {
  type: 'object',
  properties: {
    a: {
      type: 'string'
    }
  }
};

let validate = makeValidator(schema);

({ a: 10 }).should.be.validForSchema(validate);
//throws AssertionError: to be valid for schema. Errors: Object { field: 'data.a', message: 'is the wrong type' }
```

**Comment by kruncher** [comment]
@btd thanks, yes that is a good idea!

**Comment by btd** [comment]
@kruncher i just noticed i did a typo in assertion example, more correct to use this.params.operator instead of this.params.message (second one replaces message completely, but operator try to generate useful message).

**Comment by btd** [comment]
Added in 8.3.0
