### ISSUE TITLE
Improve the output when a promise was expected to be fulfilled but was rejected

### ISSUE THREAD

**Issue by jamlen** [shouldjs/should.js#105]
When a promise is rejected which you are expecting to be resolved, the output should report what it was rejected with. Currently I have to go and find the test and change it from `thing.should.be.fulfilledWith(expected)` to `thing.should.be.rejectedWith(expected)` so that it tells me why it was rejected.

Assuming that the function rejects with `{ message: 'Cannot read property \'startDate\' of undefined' }`

### Currently:
```
AssertionError: expected [Promise] to be fulfilled
```

### Desired:
```
AssertionError: expected [Promise] to be fulfilled but was rejected with { message: 'Cannot read property \'startDate\' of undefined' }
```

**Comment by btd** [comment]
Yes, make sense :+1:

**Comment by btd** [comment]
Pls, try 8.3.0

**Comment by jamlen** [comment]
That is super awesome! Thanks for turning that round so quickly
