### ISSUE TITLE
should 6.0 used to work with amd but 8.3 does not?

### ISSUE THREAD

**Issue by ca0v** [shouldjs/should.js#107]
I have code which uses requirejs and should.  Since updating from 6 to 8.3 it seems the amd aware loader has been removed.  How does one use should + requirejs?

**Comment by btd** [comment]
Hi, sorry, it was removed not intentionally. I will take a look when it has been disappear.

**Comment by ca0v** [comment]
Great.  Here is a workaround for the time being:

    define(["require", "exports", "../../../globals", "should"], function (require, exports, globals) {
        "use strict";
        var should = window.should;

**Comment by btd** [comment]
Can you please try 8.3.1. I fixed bundle.

**Comment by btd** [comment]
I am closing this issue, @ca0v. Feel free to reopen if it is not fixed for you.
