### ISSUE TITLE
calledOnce / calledTwice etc. is not a function

### ISSUE THREAD

**Issue by marcofranssen** [shouldjs/should.js#109]
Hi.

Somehow I can't manage to use the calledOnce etc on sinon stubs, spies etc. as show in the docs.

It gives me following error when running the tests.
> TypeError: connectSpy.should.be.calledTwice is not a function

I'm running the tests with **mocha**.

## Node.js version?
4.4.3

## Should.js version?
8.3.1

## How to reproduce it?
`npm install sinon@1.17.4`

```
'use strict';

const sinon = require('sinon');
const should = require('should');
const mongoose = require('mongoose');

describe('test', function () {
    let sandbox, connectStub;

    before(function () {
        sandbox = sinon.sandbox.create();
        connectSpy = sandbox.spy(mongoose, 'connect');
    });

    after(function () {
        sandbox.restore();
    });

    it('some stuff', function (done) {
        connectSpy.should.be.calledTwice();
    });
});
```

**Comment by btd** [comment]
Hi.

You have no call of `should-sinon`

**Comment by marcofranssen** [comment]
That resolves it, might be an idea to update the docs regarding those assertion methods. For me it wasn't clear that you also have to install should-sinon
