### ISSUE TITLE
Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by fatfisz** [shouldjs/should.js#111]
#### Node.js version?
6.0.0
#### Should.js version?
8.3.1
#### How to reproduce it?
`should([Symbol()]).be.eql([Symbol()]);`

I'm getting this error:
```
TypeError: Cannot convert a Symbol value to a string
    at Array.toString (native)
    at eqInternal (project_path\node_modules\should-equal\index.js:268:21)
    at checkPropertyEquality (project_path\node_modules\should-equal\index.js:55:12)
    at eqInternal (project_path\node_modules\should-equal\index.js:283:13)
    at eq (project_path\node_modules\should-equal\index.js:343:11)
    at Assertion.<anonymous> (project_path\node_modules\should\lib\ext\eql.js:44:18)
    at Assertion.Object.defineProperty.value (project_path\node_modules\should\lib\assertion.js:147:14)
```

Note the arrays - `should(Symbol()).be.eql(Symbol());` doesn't throw. I'm not sure if it shouldn't though?

At first glance this seems similar to #87, but this time it's the `should-equal` submodule, and not `should-format`.

**Comment by btd** [comment]
Thanks. That was a bug in should-equal really. Pls, try should.js 8.3.2.

**Comment by fatfisz** [comment]
Checked and it doesn't throw now. Thanks!

But still, should two different symbols be considered equal? Even this doesn't throw:
```js
should(Symbol.for('a')).be.eql(Symbol.for('b'));
```

**Comment by btd** [comment]
well, now `should-equal` does not have any support for symbols (everything unkonwn treated like object by default). I think right idea there to use === always for symbols. If you symbol from global registry (Symbol.for) you can get them equal or not. But if you create symbols with constructor you always get unique. 
What do you think?

**Comment by fatfisz** [comment]
Yes, I think that `===` should always be used for comparing Symbols. Even if it's a comparison like `Symbol() === Symbol()`, where the two symbols both "have the same key": `undefined`, but they are different still.

**Comment by btd** [comment]
Ok, 8.4.0 should do this.

**Comment by fatfisz** [comment]
I did a few checks and it looks good. Thanks for your hard work!
