### ISSUE TITLE
New browser rollup process doesn't expose window (this)

### ISSUE THREAD

**Issue by absynce** [shouldjs/should.js#112]
## Versions
```
chrome@51.0.2704
node@5.1.0
should@9.0.0
```

## How to reproduce it?
When `/should.js` is included in the browser, `this` is undefined in the `outro` script on:
```
this.Should = should;
```

## Potential resolution
I can fix the _generated file_ by passing `this` into the IIFE. 

Then I defined `root` as the parameter and changed the outro to:
```
root.Should = should;

Object.defineProperty(root, 'should', {
```
This resolved the error.

I can't yet figure out how to pass `this` or `window` into the rollup process. I'm thinking it would be something like [this example](https://github.com/rollup/rollup/issues/556#issue-141313282).

**Comment by btd** [comment]
Thanks. It should be fixed in 9.0.1.
