### ISSUE TITLE
`.should.not.have.properties([ ])` does not fail if a listed properly does exist

### ISSUE THREAD

**Issue by benbuckman** [shouldjs/should.js#114]
The [`.should.have.properties`](http://shouldjs.github.io/#assertion-properties) assertion allows an array input of keys. Example from the docs: `({ a: 10, b: 20 }).should.have.properties([ 'a' ]);`.

So given `obj = { foo: 'bar' }`, you can do `should(obj).have.properties(['foo', 'zoo']);` and it fails because there is no `zoo` property.

I would expect the inverse `.not.have.properties` to fail when any property in the array _does_ exist. For example, given `{ obj = foo: 'bar' }`, and the assertion `should(obj).not.have.properties(['foo']);`, it fails (correctly). But given that same object and the assertion `should(obj).not.have.properties(['foo', 'zoo']);`, it _does not fail_.

This kind of makes sense, because it's negating the `.should.have.properties(['foo', 'zoo'])`, and it does not have both properties. However, intuitively I would expect `.should.not.have.properties([ ])` to be asserting that it has _none_ of those properties, and it does not do that.

Is this a bug, or by design?
Thank you!

- Node.js version: 4.4.2
- Should.js version: 8.2.2

**Comment by btd** [comment]
Hi. We have such issue in past. You can add `.any` modifier to make it assert when missing any of properties. Literally it means default behaviour of .properties to check **all** properties.

**Comment by benbuckman** [comment]
Thanks @btd!

**Comment by btd** [comment]
Welcome!
