### ISSUE TITLE
should is undefined

### ISSUE THREAD

**Issue by Creatan** [shouldjs/should.js#116]
## Node.js version?
4.4.4
## Should.js version?
7.1.0
## How to reproduce it?
I'm using mocha and should.js for testing and sometimes when requiring should.js in the following way leads to behavior where the should variable is undefined but Object.prototype has should inserted properly.

```
var should = require('should');  
console.log(should); // undefined

var obj = {};
should(obj).be.empty(); // TypeError: __get(...)__ is not a function  
obj.should.be.empty(); // works
````

The following is a one workaround for the issue
```
var Should = require('should');
````
now doing assersions with `Should` work as expected, but I don't believe that this kind of behavior is desired.

**Comment by btd** [comment]
That is really very strange. I could not reproduce this in any way. Because if 
```
var should = require('should');  
console.log(should); // undefined
```
Returns undefined, you have some problems with your installation. For me it looks like you have global ly defined getter .should in your host object.
Can you provide more information? even better will be reproducible example. Also could you publish your package.json and how you run your script?

**Comment by Creatan** [comment]
With further testing I found out that if I run just the offending file with mocha everything works, but if I run the full test-suite then it breaks. So the issue is not with should.js but something in the suite is doing something it propably shouldn't.

**Comment by killmenot** [comment]
Got the same issues when https://github.com/speedskater/babel-plugin-rewire is used

For some reason
```js
import should from 'should'
```
doesn't work but
```js
import Should from 'should'
```
works fine

**Comment by btd** [comment]
@killmenot i need more details what you are doing. Ideally reproducible example. Browser bundle do not have es6 exports.

**Comment by killmenot** [comment]
@btd I believe that in my case the issue is not related with `should.js` It worked fine before I added `babel-plugin-rewire` to my code. I'll try to isolate a problem

**Comment by btd** [comment]
@killmenot  ok, let me know if can help.
