### ISSUE TITLE
abstract/loose equality assertion?

### ISSUE THREAD

**Issue by tonylukasavage** [shouldjs/should.js#122]
In looking through the API docs, it seems as though there's only assertions for strict equality (`===`). Am I missing a function somewhere, or is only strict equality supported? If only strict equality is supported now, would you be open to a PR for adding abstract/loose equality (`==`)? Perhaps something along the lines of:

```js
var foo = '123';
foo.should.looseEqual(123);
```

I'm obviously very open to alternatives to the function name, I just threw `()` out there to start the conversation.

**Comment by btd** [comment]
I am open to PR in general, but it a bit sounds strange. I could not imagine where current .equal and .eql 
'equality' assertions do not suite. 
Could you please describe your real use case? Or it is just something potential.
In past i did not added == because it is adding more confusion (3 assertion equality methods) and allow literally to shoot in the foot.

**Comment by tonylukasavage** [comment]
The real use case for me is I have a unit test where I want to assert that both my express route is returning the right status code, and that my JSONAPI serialized response also has that same response code. The problem is that express returns it as a number, and JSONAPI expects status as a string.

so in my case I have something like this (abridged):

```js
let status = 401;
request.post({ url }, function(err, resp, body) {
  resp.statusCode.should.equal(status);

  // wish I could do this:
  // body.errors[0].status.should.looseEqual(status);
  body.errors[0].status.should.equal(String(status));
});
```

We check this in tons of places. It's by no means critical and converting the value explicitly works. Was more wondering what the maintainers thought and if any other users of should.js would find this useful, and if I wrote a PR if it would get merged.

**Comment by btd** [comment]
I got you. But to me it looks you just need to extend should yourself for your project (as your usecase pretty valid for your project mostly, but outside it is something questinable).

**Comment by tonylukasavage** [comment]
Yep, I'm extending it now. I'll close this for now. If in the off-chance others have more valid use cases they can drop a comment here and you can revisit.

**Comment by btd** [comment]
Thank you. 👍 Awaiting feedback.
