### ISSUE TITLE
Error in .keys() method

### ISSUE THREAD

**Issue by posquit0** [shouldjs/should.js#127]
- Node.js version: v6.9.1
- Should.js version? 11.1.1
- How to reproduce it?

I got the below error message after updating `should` package from `10.0.0` to `11.1.1`.
It doesn't have any error before.

```node
 Uncaught AssertionError: expected Object {
  expiry: Object {
    ...
  },
  registrationNumber: Object {
    ...
  },
  password: Object {
    ...
  }
} to have key expiry,registrationNumber,password
        missing keys: expiry,registrationNumber,password
```

**Comment by btd** [comment]
Hi.

Can you provide please provide test case, that i can run and reproduce?

**Comment by posquit0** [comment]
Hi!
I think a behavior of `.keys()` was changed between ver `10.0.0` and `11.1.1`.

```node
> obj = {a:1, b:2, c:3}
> obj.should.have.keys(['a','b','c'])
// Assert in 11.1.1, No Assert in 10.0.0
> obj.should.have.properties(['a','b','c'])
// No Assert in 11.1.1
```

I have two questions.
- Why doesn't work above code as intended with ver `11.1.1`?
- What's the differences between `.keys()` and `.properties`?

**Comment by btd** [comment]
This was breaking change for 11.x. Please always check [this url](https://github.com/shouldjs/should.js/wiki/Breaking-changes) when doing major upgrades.

Keys and properties in 11.x have very big differences.
* `.properties` always check **object** properties (everything considered an object)
* `.keys/.key` checks for __keys__: for object it is hasOwnProperty, for Map/Set/WeakMap/WeakSet it is .key method, for immutable.js similar.

**Comment by posquit0** [comment]
Thanks!

**Comment by btd** [comment]
Welcome 👍
