### ISSUE TITLE
odd results with .should.be.fulfilled()

### ISSUE THREAD

**Issue by jmls** [shouldjs/should.js#129]
I'm not sure what is happening here. I have a method that returns a promise (which, at the moment *always* rejects the login)

```js
        /**
         * login a user and get a sessionId
         * @param {string} username The user name
         * @param {string} password The user password
         * @param {function} [callback] The callback function
         */
        login(username: string, password:string, callback:Function) {
            debug("login not implemented");

            return new Promise((resolve,reject) => {
                return callback ? callback(null,{}) : reject("invalid username or password");
            });
        };
```

and this is my test

```
it('should fail with invalid username',  (done) => {
  sessionModel.login("bar","foo").should.be.rejected();
  done();
});

it('should pass with a user name of "foo" and a password of "bar"',  (done) => {
  sessionModel.login("foo","bar").should.be.fulfilled();
  done();
});
```

the "invalid username" test passes, *and so does the valid username* : even though there are errors pn the screen

![image](https://cloud.githubusercontent.com/assets/929523/21257397/e7b0be10-c36f-11e6-96c0-2a5279f01608.png)

## Node.js version? : 7.0.0 / 7.2.0 / 4.6.1

4.6.1 does not show the errors on the console, but still passes the test

**Comment by btd** [comment]
There problem in your test cases. Your method returns Promise, but you never wait for it to finish.
You should do something like this (in case of mocha):
```js
it('should pass with a user name of "foo" and a password of "bar"',  () => {
  return sessionModel.login("foo","bar").should.be.fulfilled();
});
```

**Comment by jmls** [comment]
ah! perfect - thanks very much. it's now working as expected.
