### ISSUE TITLE
odd should.throw behaviour

### ISSUE THREAD

**Issue by jmls** [shouldjs/should.js#130]
I have a strange thing happening with a throw ..

I have a function defined as such:

```
 this.setToken = (token) => {
    throw new Error("invalid fuzzball");
}
```

and I'm testing that it should throw an error

```
describe('when performing a fuzball, it', () => {

    it('should throw test#1',  (done) => {
        (function(){ throw new Error('fail') }).should.throw();
        done();
    });

    it('should throw test#2',  (done) => {
        someLib.setToken("foo").should.throw();
        done();
    });

}),

```

however, I'm getting the following on the console:
![image](https://cloud.githubusercontent.com/assets/929523/21287130/af018390-c45c-11e6-98a7-0622a5ae57ea.png)
![image](https://cloud.githubusercontent.com/assets/929523/21287135/bdce61e0-c45c-11e6-8742-7a39a7ee7b62.png)

what am I missing ?

**Comment by btd** [comment]
.throw checks if given function, when called throw error. You call .setToken your self, but it should be called by should.js.
```js
(() => someLib.setToken('foo')).should.throw()
//or
someLib.setToken.bind('foo').should.throw();
```
