### ISSUE TITLE
JavaScript heap out of memory using .property(name, value) against Sequelize wrapper object

### ISSUE THREAD

**Issue by xxxtonixxx** [shouldjs/should.js#136]
Hi.

Answer several questions if it is a bug:

## Node.js version?
v7.2.1
## Should.js version?
v11.2.0
## How to reproduce it?
I get a core dump, the test gets frozen and my CPU is 100% when I'm doing an assert against a Sequelize object wrapper :
```javascript
Users.findOne({
          where: {
            id: 1
          }
        }).then(user => {
                user.should.have.property('name', 'toni');
       })
```
It generates the following core dump:
![spectacle ak1504](https://cloud.githubusercontent.com/assets/7110786/22704923/c23560e0-ed69-11e6-9ad2-b58507343961.png)

It only happens when I use `.property(name, value)`. However, when I use, `.property(name).be.eql(value)`, it works properly.

```javascript
Users.findOne({
          where: {
            id: 1
          }
        }).then(user => {
               // It works well
                user.should.have.property('name').be.eql('toni');
       })
```

If I want to use `.property(name, value)`, I need to get a plain object (whitout Sequelize's wrapper), like this one:
```javascript
// user.get() returns a plain object
user.get().should.have.property('name', 'toni');
// This would be the representation of the object
const userWhitoutWrapper = {
         id: 1,
         name: 'toni',
}
```

The Sequelize's wrapper looks like this:
![spectacle wy1504](https://cloud.githubusercontent.com/assets/7110786/22705592/67be7b08-ed6c-11e6-844b-1acae2ace979.png)

**Comment by btd** [comment]
Can you please provide me more information:
1. How your model looks and what datatypes is (sql create table literally, and how sequalize handle it)
2. Versions of libs (pg, sequalize etc)
3. Should your assertion throws? or it is out of heap even on succcessful assertion?

It would be very nice if you create self replicating example for me. Instead of me creating project from scratch to replicate issue.

**Comment by btd** [comment]
Also i am interesting how sequalize wrapper handles properties - is it getters or just copied values, or even Proxy? Any ideas?
