### ISSUE TITLE
should(undefined).match(/bar/) is not a failed assertion

### ISSUE THREAD

**Issue by arnoldmanzano** [shouldjs/should.js#137]
Hi.
This does not seem intuitive but the mentioned assertion does not result to a failed test.
It was encountered when testing an object that was expected to be a string to match the given RegExp. The object was undefined but the test did not fail.

## Node.js version?
6.9.1

## Should.js version?
"should": "^11.1.1"

## How to reproduce it?
Use the following assertion, test passes.
`should(undefined).match(/bar/);`

Thanks!

**Comment by btd** [comment]
Hi, thanks.

Please try 11.2.1.

**Comment by arnoldmanzano** [comment]
Thanks for the update. 👍
