### ISSUE TITLE
not using semicolon throw error

### ISSUE THREAD

**Issue by mxyue** [shouldjs/should.js#138]
## Node.js version

7.5.0

## Should.js version

11.2.0

## example

```
    [ 1, 2, 3].should.containDeep([2, 1])
    (10).should.be.eql(10)
```
it will throw error
 > TypeError: [1,2,3].should.containDeep(...) is not a function

I must use semicolon

```
   [ 1, 2, 3].should.containDeep([2, 1]);
   (10).should.be.eql(10)
```

why? I don't like using semicolon.

**Comment by btd** [comment]
Not sure what you want i suggest there. It is javascript you cannot do everything you do not like.
This happen because of two expression statement is going one after another, and they are not separeted by any operator.
Closing as it does not look like i can do anything.
