### ISSUE TITLE
rejected(param) silently ignores parameter

### ISSUE THREAD

**Issue by merriam** [shouldjs/should.js#142]
This invalid code:

      findQuestion(42).should.be.rejected(/not found/)

looks like this valid code to a new user:

     findQuestion(42).should.be.rejectedWith(/not found/)

except that it doesn't work.  The parameter `/not found/` is ignored.

Option 1: throw an error so the user knows the test doesn't do what she expects (`Usage error:  Did you mean .rejectedWith?`).
Option 2: do what she expects anyway (call `rejectedWith` if a parameter is passed).

As of Node v7.9.0, Should.js v11.2.1.

**Comment by btd** [comment]
I think i will throw error about zero number of expected arguments. Passing some sort of defaults usually beat later.

**Comment by btd** [comment]
While i think it is bad, but i also think it is not worth to spend time on this. If someone care i think it is right to try TS of flow (at least ts typings available).

I will rest this open, if i will get better idea i will add something.

**Comment by btd** [comment]
This is fixed

**Comment by merriam** [comment]
:)
