### ISSUE TITLE
async functions don't work as expected with throw() assertion

### ISSUE THREAD

**Issue by tonylukasavage** [shouldjs/should.js#144]
Essentially, if you attempt to use the `throw()` assertion with an `async` function, it will fail to assert properly. 

## Node.js version? 

7.9, 7.8

## Should.js version? 

11.2.1

## How to reproduce it?

```
let should = require('should');
(async function() {
	throw new Error('fail');
}).should.throw('fail');
```

produces the output:

```
/Users/tony/development/should-bug/node_modules/should/cjs/should.js:237
      throw new AssertionError(params);
      ^
AssertionError: expected Function { name: '' } to throw exception
    at Assertion.fail (/Users/tony/development/should-bug/node_modules/should/cjs/should.js:258:17)
    at Assertion.value (/Users/tony/development/should-bug/node_modules/should/cjs/should.js:335:19)
    at Object.<anonymous> (/Users/tony/development/should-bug/index.js:5:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
```

## possible resolution

There's an area of the lib/ext/error.js file that could be modified to support this, BUT it is unfortunately not simple since there's no real concept of handling async functions in assertions at this point. Specifically:

https://github.com/shouldjs/should.js/blob/master/lib/ext/error.js#L54

If instead of just invoking `fn()` here you instead check to see if the function is `async` (a similar quick and dirty check like generators) and if it is, call `await fn()` instead. This of course requires the containing function to be `async`, which in turn screws up all the existing `throw()` assertion tests. So while handling these async functions with the throw() assertion isn't that hard, it is in fact hard, and may require some heavier lifting, to make it work side-by-side with the existing synchronous cases of throw().

**Comment by btd** [comment]
Well, because of a mix of terms like function and async this could looks strange. But async function still a function returning promise. So you can just do:
```js
$ node
> const should = require('.')
undefined
> let f = async function() { throw new Error('boom') }
undefined
> f
[AsyncFunction: f]
> f()
Promise {
  <rejected> Error: boom
> (node:4052) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: boom
(node:4052) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js
 process with a non-zero exit code.

> f().should.be.rejected()
Promise { <pending> }
>

```

I am not sure if i should add promises support to .throw (probably should? because generators there so why not).

**Comment by tonylukasavage** [comment]
So `rejected` and `rejectedWith` work, when they work. Let me explain with a slightly modified case:

```
❯ node
> const should = require('should');
undefined
> async function foo() {
... 	throw new Error('foo');
... }
undefined
> foo().should.be.rejectedWith('foo');
Promise { <pending> }
```

The above does exactly what I need. Asserts that the Promise is rejected with the value `'foo'`. Unfortunately, though, `should` doesn't give me an error when it does not match the string. For example:

```
❯ node
> const should = require('should');
undefined
> async function foo() {
... 	throw new Error('foo');
... }
undefined
> foo().should.be.rejectedWith('foo1');
Promise { <pending> }
> (node:85568) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): AssertionError: expected [Promise] to be rejected with a message matching 'foo1', but got 'foo'
(node:85568) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

So the problem that remains is that it's not giving me an assertion-breaking error when the Promise does not match the string, it's giving me the node.js `UnhandledPromiseRejectionWarning`, but it's not actually failing the assertion and then continues as though nothing is wrong.

Is this is a bug with rejectedWith(), or am I doing something wrong here?

**Comment by msenevir** [comment]
also noticed this, and have also seen the same issues with chai

For reference, here is the thread on the chai project: https://github.com/chaijs/chai/issues/415

+1 for using throws, I think it better expresses the intent of writing code in this synchronous fashion

**Comment by btd** [comment]
@tonylukasavage sorry but in your last example number of issues. You are getting only half of the picture.
I created simplified test case to explain you better:
```js
const should = require(".");

async function foo() {
  throw new Error("AAA");
}

function it(name, callback) {
  var res = callback();
  if (res != null && typeof res.then === "function") {
    return res.then(() => console.log(name, "Ok"), err => console.error(name, err.stack));
  }
}

it("async/await rejected positive pass (no assertion)", async () => {
  await foo().should.be.rejected();
});

it("async/await rejected positive assert (assertion is ok)", async () => {
  await foo().should.be.rejectedWith("BBB");
});

it("async/await fulfilled assert (assertion is ok)", async () => {
  await foo().should.be.fulfilled();
});
```

After exectution you will get something like this in console:
```
$ node test.js
async/await rejected positive pass (no assertion) Ok
async/await rejected positive assert (assertion is ok) AssertionError: expected [Promise] to be rejected with a message matching 'BBB', but got 'AAA'
    at next$onError (D:\Projects\shouldjs\should.js\cjs\should.js:1696:12)
    at runMicrotasksCallback (internal/process/next_tick.js:64:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
async/await fulfilled assert (assertion is ok) AssertionError: expected [Promise] to be fulfilled, but it was rejected with Error { message: 'AAA' }
    at Assertion.fail (D:\Projects\shouldjs\should.js\cjs\should.js:258:17)
    at next$onReject (D:\Projects\shouldjs\should.js\cjs\should.js:1522:14)
    at runMicrotasksCallback (internal/process/next_tick.js:64:5)
```
So as you see it throw where it should and pass where it should.

You are getting some false sence of sync code, but to make it look async you do not use await where you should (to get promise value).

Please let me know if it still unclear. Or maybe i do not really understand whay you mean.

**Comment by btd** [comment]
@msenevir You linked issue i think is not about the same Tony has. You are rightly using .eventually + .throw so internal context will be switched to handling promises.
I believe your example will work fine/similar there.

**Comment by tonylukasavage** [comment]
@btd i see how you resolved the issue I was having with `rejected`, thank you. It was a sloppy natural progression from the `throw()` test (to which I'm accustomed) to the `rejected` tests which I hand't yet used.

I'll leave it up to you whether or not you want to keep this issue open to address handling this in the `throw()` assertion

**Comment by btd** [comment]
@tonylukasavage i am not sure about modifying .throw is a right idea. I am worrying this will create confustion, between sync and async assertions.
I will rest this open, maybe some other folks could add something to this.

**Comment by btd** [comment]
@msenevir @tonylukasavage 

I wrote promise assertion that way - after you call .eventually/.finally assertion switching to use promises and all methods of usual assertion will work as expected, but with `.throw` it is a bit different, as `.throw` expecting as an input function or generator. But as an input using `foo()` we are getting already rejected promise.
The best i can do currently:
```js
it("async/await .finally/.eventually proxy all assertions", async () => {
  await foo().should.finally.be.Error();
});
```

This is because await make it look sync, and promise returing Error.
I finally think overriding .throw for promises is not right, this is too different concepts. It is better to educate users do right thing.
