### ISSUE TITLE
Runtime error when typings are installed

### ISSUE THREAD

**Issue by cohenadair** [shouldjs/should.js#147]
My apologies if you have nothing to do with `@type/should`; I couldn't find the typings source. If the typings is something separate, not managed here, feel free to close this issue.

## Steps to reproduce
* `npm install @type/should --save-dev`
* `npm test`
```
node_modules/@types/should/index.d.ts(7,3): error TS2403: Subsequent variable declarations must have the same type.  Variable 'should' must be of type 'Assertion', but here has type 'ShouldAssertion'.
```

**Comment by btd** [comment]
This typings is not maintained by me.
I can try to fix this, but i never used typescript. Can you provide me more details:
1. What versions you are using: node and ts?
2. Do you have ideas where is a repo with this typings? I tried to search but stuck a bit.

It is probably makes sence to move ts definitions to this repo, but as i said i do not have any expirience in this area - so i could become invalid or outdated.

**Comment by btd** [comment]
It looks it is this one https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/should/index.d.ts
I will try to update it, but as i said i have not experince in this, so this could take some time.

**Comment by cohenadair** [comment]
I'm using Node 9.5.1 and TypeScript 2.3.4.

The typings add a "should" property to Object, which seems conflicts which another library I'm using; although I can't find which. As far as I can tell, the typings only apply when you're using the Object extension.

Also, that typings is for should.js 8.3.0, which is a very old version. I'm using should.js 11.2.1.

**Comment by btd** [comment]
They seem updated it too 11.2. I will try to send them PR, when i do updates in future

**Comment by btd** [comment]
@cohenadair sorry for bother, if it is not hard could you pls, try my typings for shouldjs. It is in root of repo.

Thanks

**Comment by cohenadair** [comment]
@btd Everything seems to be okay now; although, I'm not sure I'm using the exact same environment I did when I had this issue. I have since moved on from JavaScript-based languages, but a quick test says it's working as expected.

**Comment by Koslun** [comment]
@btd I am still seeing this error from the typings  in the root of the project. This is the specific error message now:
```
node_modules/should/should.d.ts(237,5): error TS2717: Subsequent property declarations must have the same type.  Property 'should' must be of type 'Assertion', but here has type 'Assertion'.
```

So the error now points to this line: https://github.com/shouldjs/should.js/blob/9748ae607f80fbf544d4bb67db8e1e014de2301f/should.d.ts#L237

Simply removing that global declaration fixes it for me as I do not ever use should as a global but assuming that it's a valid use-case I figure there should be a solution where you can still have it on the global scope. I just don't yet understand why this error occurs.
