### ISSUE TITLE
which should.js to use in browser

### ISSUE THREAD

**Issue by kofifus** [shouldjs/should.js#148]
I did `npm install -g should.js`

I now have:

C:\Users\me\AppData\Roaming\npm\node_modules\should\es6\should.js
C:\Users\me\AppData\Roaming\npm\node_modules\should\cjs\should.js
C:\Users\me\AppData\Roaming\npm\node_modules\should\should.js

all of different sizes.

Which one should I use in the browser ?

**Comment by btd** [comment]
Last one
