### ISSUE TITLE
Could not assert undefined

### ISSUE THREAD

**Issue by taoqf** [shouldjs/should.js#149]
Hi.

Answer several questions if it is a bug:

## Node.js version?
8.4
## Should.js version?
11.2.1
## How to reproduce it?
1. do not require should in test.js, or `require('should');` not `const should = require('should');`
2. use mocha --require should  test.js

**Comment by btd** [comment]
Hi, can you pls write exact commands you execute and test.js content?

**Comment by taoqf** [comment]
test.js
```js
require('should');
descript('test', function(){
  it('undefined', function(){
    should(undefined).be.undefined();
  });
});
```
command:
```sh
mocha test.js
```

**Comment by btd** [comment]
In first case there is no `should` variable, so how you suppose to call function if it is not defined?

The same applied when mocha require it, should valiable is not defined.

This ways only works for getter form like `(10).should.be.Number()`.

**Comment by taoqf** [comment]
there is a global `should` after i required should, but it is not a funciton.

**Comment by btd** [comment]
there is no global `should`. As should added to Object.prototype in this case. Global object also will have this getter and what you call global should - it is a getter. And yes in this way you cannot test this way for null or undefined, but not because of should.js but because js works this way.

**Comment by taoqf** [comment]
I know what you mean, I do wish this could be support. may global `should` could also be a function? i don't want require `should` in my test files.

**Comment by taoqf** [comment]
btw, in `@types/should`, 
```ts
interface Internal extends ShouldInternal {
  (obj: any): ShouldAssertion;

  // node.js's assert functions
  fail(actual: any, expected: any, message: string, operator: string): void;
  assert(value: any, message: string): void;
  ok(value: any, message?: string): void;
  equal(actual: any, expected: any, message?: string): void;
  notEqual(actual: any, expected: any, message?: string): void;
  deepEqual(actual: any, expected: any, message?: string): void;
  notDeepEqual(actual: any, expected: any, message?: string): void;
  strictEqual(actual: any, expected: any, message?: string): void;
  notStrictEqual(actual: any, expected: any, message?: string): void;
  throws(block: any, error?: any, message?: string): void;
  doesNotThrow(block: any, message?: string): void;
  ifError(value: any): void;
  inspect(value: any, obj: any): any;
}

declare var should: Internal;
```

it do seems like global `should` is a function, too.

**Comment by btd** [comment]
This is mistake in that repo - i have no control over it. There is another bug was with that typings (https://github.com/shouldjs/should.js/issues/147). 
I have plans to write typings myself and keep in this repo, but without exp in ts and lack of time... it is hard a bit.

**Comment by btd** [comment]
I would not add what you asking because it would be breaking change. I can plan this for future if some more people will ask for this. There is no problem and i do not against it.

For now i would suggest you to use something like this. Create file should-global.js with content:
`global.should = require('should')`
and require it instead of should (with local path). Maybe it would need to use `Object.defineProperty(global, 'should', { value: require('should') })`. Something like this

In theory this should work (i did not test).

**Comment by taoqf** [comment]
thanks anyway

**Comment by btd** [comment]
Welcome.

I looked what types in DefinetlyTyped, and noticed that they uses what is in browser bundle (should.js file in the root of repo). In that bundle there is window.should which is not getter, but function. 
So i think you are right (i need to make browser bundle and node module look similar), and i will add this next major release (should be soon enought as i have breaking change in eql module).

**Comment by btd** [comment]
@taoqf sorry for bother, if it is not hard could you pls, try my typings for shouldjs. It is in root of repo.

Thanks

**Comment by taoqf** [comment]
I will try

**Comment by taoqf** [comment]
Sorry, I'm afraid I could do all the tests, because  I just use this module in my tests(all test file is js file), it would be always fine in js. maybe someone who use ts test would help us.
btw, maybe there will be a pr in https://github.com/DefinitelyTyped/DefinitelyTyped needed to remove @types/should if a new version released in npm.
