### ISSUE TITLE
iife bundle missing from v13

### ISSUE THREAD

**Issue by reblace** [shouldjs/should.js#151]
Looks like the latest published npm artifact is missing the iife build. In other words, should.js is missing from the root of the project. That means I can't use should.js in the browser without either building it manually or using v11.2 (or transpiling the es6 version). I didn't see anything that suggested this omission was intentional. Thanks!

**Comment by btd** [comment]
ohh, sorry for this, will fix this in few minutes.

**Comment by btd** [comment]
This should be fixed now 13.0.1
