### ISSUE TITLE
Alias `fulfilled/fulfilledWith` as `resolved/resolvedWith`

### ISSUE THREAD

**Issue by tsclaus** [shouldjs/should.js#152]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise|

Fullfill and Resolve are somewhat interchangeable when it comes to promises but this library currently only supports the former. Can I make a simple PR that just aliases the two missing functions?

**Comment by btd** [comment]
Yes, PR welcomes. You need:
1. Modify lib/ext/promise.js adding alias, modify jsdoc comment (you can see examples in other files also).
2. Modify should.d.ts adding new methods
3. Add test cases (enough very simple, just that method exists).

**Comment by btd** [comment]
This is fixed
