### ISSUE TITLE
should.throws doesn't catch the error when it fails to match it

### ISSUE THREAD

**Issue by tsclaus** [shouldjs/should.js#153]
When using `should.throws`, if the `error` parameter you are matching against doesn't match the thrown error, instead of catching the error and logging actual vs expected (like most assertions), it doesn't catch the error at all.

Example:
```
'use strict';

const assert = require('assert');

const should = require('should');

describe.only('stub for missing method', function() {
  beforeEach(function() {
    this.testFn = function() {
      throw new Error('aaa');
    };
  });

  it('should pass when a matching error is thrown', function() {
    //assert.throws(() => this.test(), /aaa/);
    should.throws(() => this.testFn(), /aaa/);
  });

  it('should error with an expectation not "aaa"', function() {
    //assert.throws(() => this.test(), /bbb/);
    should.throws(() => this.testFn(), /bbb/);
  });
});
```
logs
```
1) stub for missing method should error with an expectation not "aaa":
     Error: aaa
      at Context.testFn (test.spec.js:10:13)
      at should.throws (test.spec.js:21:30)
      at Function._throws (node_modules/should/cjs/should.js:686:5)
      at Function.assert.throws (node_modules/should/cjs/should.js:719:11)
      at Context.<anonymous> (test.spec.js:21:12)
```

Is this intended behavior? It seems unintuitive and I can't think of a use for it besides nesting `should.throws` inside it's first argument or something to do with sequenced assertions and `any` (I can't find documentation for those concepts). At any rate, `rejectedWith` will show actual vs expected rather than letting the promise reject if the argument doesn't match which is inconsistent with `throws`.

**Comment by btd** [comment]
Yes this is intendent behaviour. I did port nodejs 0.xx assert module in 2015, at that time it does not have such interface. I do not think it is worth my time to keep it up to date (i would remove it).
Also you mixed static should functions which is literally assert functions implemented using should.js methods, another thing you did wrong it is about `any` and `rejectedWith` first workin only with `.properties` and second working only with promises. (I highly recommend you first read api docs)

**Comment by tsclaus** [comment]
Here are the docs for `any`:

`Any modifier - it affect on execution of sequenced assertion to do not check all, but check any of.`

Not a lot to read up on. And I'm forced to mix static methods because that is the only way to test synchronous throwing, maybe that could be the change; but error matching for synchronous errors should using the same same matching you use for asynchronous error matching, which is currently impossible. And I don't think `rejectedWith` works with non promises given:

```
Assert given promise will be rejected with some sort of error. Arguments is the same for Assertion#throw.
Result of assertion is still .thenable and should be handled accordingly.
```

It says it works for only promises.

**Comment by btd** [comment]
About docs for `any` i agree. Need to add more.
About sync and async throws you are completly wrong, :
```js
function simpleFunction() {
  throw new Error('boom');
}

should(simpleFunction).throw()
```

![default](https://user-images.githubusercontent.com/334851/30247355-4c628c52-961b-11e7-9904-a20f5c0c1ab2.png)

**Comment by btd** [comment]
It seems @tsclaus you do not have any more questions?
