### ISSUE TITLE
main.d.ts is broken

### ISSUE THREAD

**Issue by Spown** [shouldjs/should.js#155]
after [this update](/shouldjs/should.js/commit/c12afd0e64ee47fe69690320c56a1fb7e8076e2f) The only thing I get for Intellisence in VSCode is ``default``:

![](https://drive.google.com/uc?id=0B-OJBofmehO3T0ZCalhubkhWWWs)

Replacing ``default`` with ``=`` solves this. Please be more considerate.

Thank you.

**Comment by btd** [comment]
There was PR https://github.com/shouldjs/should.js/pull/154, about replacing = with default. This was done for supporting import statements. I do not have strong opinion on subject (i do not use ts personally), but i prefer imports whenever possible.

I will rest this open, to get more opinions about this.

**Comment by FengBryan** [comment]
but now ,use this way 
```
import should from 'should'
```
throw the error: 
```
     TypeError: should_1.default is not a function
```

**Comment by Spown** [comment]
> (i do not use ts personally), but i prefer imports whenever possible

@btd well, I develop in pure js - I don't have the luxury of preferring. main.d.ts is consumed in the background by ts through VSCode to produce Intellisence. I can't just jump onto some new way. @citizensas  can use another way for import - he is not restricted. He made a PR that only covers TS12 and he didn't care for backwards or any sort of compatibility whatsoever. I think you should revert it to "=" and he should produce a proper PR that is widely compatible, with tests and such.

thank you.

**Comment by FengBryan** [comment]
@Spown i agree with u, now is some wrong happen with my test cases writen by typescript(can not compile and run correctly).  this PR should covered by tests before it  merged

**Comment by btd** [comment]
@Spown @FengBryan glad to see this discussion. As i said i do not use TS personally. If you bring PR i would consider to merge it, but please cc previous editor (please take a look to blame).

**Comment by citizensas** [comment]
I'm sorry to hear that you end up with a "breaking change". Version 13 itself came with a breaking change.
I do agree that there should be a better way to declare default export.
The recommended way is the following,
```typescript
declare module "should" {
   export = should
}
```
but TypeScript says `"should" has no default export`

I didn't realise this can be a breaking change for some of you. You can revert the PR until I find a better, more universal way to write typing declaration for should.js. 
Actually I think it'll be better to move the code from `@types/should` and do some edits to match the structure of `should@13`.

**Comment by FengBryan** [comment]
@btd  I'm so sorry about my word with discussing the PR. And I think @citizensas said take typing to types repo is the better way can make type and code both be pure.
Thanks for resolving my problem.

**Comment by Spown** [comment]
>If you bring PR i would consider to merge it

>You can revert the PR until I find a better, more universal way

please do. I don't even have a fork of should.

**Comment by btd** [comment]
@Spown 👍 , can you please test first with shouldjs 13.0.1, where it has no such problem and after this i will revert that commit.

**Comment by Spown** [comment]
As I said in OP - "Replacing default with = solves this." Which means I went to the ``node_modules/should/`` and manually changed it. after which Intellisence started working again.

**Comment by btd** [comment]
Ok, great! Will do revert.

**Comment by Spown** [comment]
just tested should@13.0.1 to be sure. it does work.

**Comment by sparebytes** [comment]
Type declarations don't work with `should/as-function`.

**Comment by btd** [comment]
@sparebytes can you please create a separate issue about this. Also please add more details, i am not ts user so as much details will help me resolve it faster.
