### ISSUE TITLE
containDeep erroneously passes when comparing array with a string value to a string value within object

### ISSUE THREAD

**Issue by seongju** [shouldjs/should.js#157]
I think I may have stumbled across a bug using `containDeep`.
![screen shot 2017-10-16 at 11 33 12 am](https://user-images.githubusercontent.com/5506190/31621507-dfd8bae8-b267-11e7-9c6a-9aa7677213a1.png)

According to the documentation, it seems that `containDeep` should have failed this assertion because for an object...
> it checks that the same keys contain deep equal values (recursive)

## Node.js version?
8.1.4
## Should.js version?
11.2.1
## How to reproduce it?
See above screenshot.

**Comment by btd** [comment]
Yep, looks like a bug to me
