### ISSUE TITLE
General query - what are common test assertions used?

### ISSUE THREAD

**Issue by kensoh** [shouldjs/should.js#158]
Hi Denis and guys, may I check from you what are common assertions that you use in your test automation? Eg check that element contains text, check element exists etc. Crowdsourcing inputs for test assertions support for a personal project. This is not an issue, please feel free to close if irrelevant.

In that project I made a wrapper around CasperJS but as CasperJS has no support for visible / headless Chrome, test assertions won't work. Working to address that, for some basic range of assertion scenarios to work with Chrome.

**Comment by btd** [comment]
There is no such thing as common assertion. You are writing test and using assertion that at least test what you suppose your test should test. 

I am closing this, but if you want to continue discussion feel free. Also try to ask in gitter chat

**Comment by kensoh** [comment]
Thanks Denis @btd ! Appreciate that you replied, ok got it.

I'll just ask around some more whether what I made is enough for common tests / scenarios for websites. I was working as a test automation engineer, but wanted to see if I miss out some use cases that other people depend on in their day-to-day testing / CI / CD.
