### ISSUE TITLE
Assertion#size(s) broken when requiring should as a function

### ISSUE THREAD

**Issue by HugoMuller** [shouldjs/should.js#163]
Hi,

**Assertion#size(s)** seems to be broken when should is required as a function.

Node.js version: 8.9.4
Should.js version: 13.2.0

## How to reproduce it?
This code works as expected:
```js
require('should');
({ a: 10 }).should.have.size(1);
should({ a: 10 }).have.size(1);
```
But this one throws an error:
```js
const should = require('should/as-function');
should({ a: 10 }).have.size(1); // same line as above
```
> TypeError: Cannot read property 'be' of undefined
>    at Assertion.<anonymous\> (<project\>/node_modules/should/as-function.js:2371:45)
>    at Assertion.value [as size] (<project\>/node_modules/should/as-function.js:337:14)

**Comment by btd** [comment]
Fixed in 13.2.1
