### ISSUE TITLE
node_modules/should/should.d.ts(237,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'should' must be of type 'Assertion', but here has type 'Assertion'.

### ISSUE THREAD

**Issue by Thavaprakash** [shouldjs/should.js#166]
Hi.

I'm getting below error, could you help me.

node_modules/should/should.d.ts(237,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'should' must be of type 'Assertion', but here has type 'Assertion'.

## Node.js version?
v8.9.1

## Should.js version?
"should": "13.1.3"

## How to reproduce it?
in test.ts
import * as should from 'should';

**Comment by btd** [comment]
Do you have chai installed? and chai typings?

**Comment by Thavaprakash** [comment]
@btd , yes i have installed.
   "devDependencies": {                                                         
     "@types/chai": "^4.1.2",                                                   
     "@types/mocha": "^2.2.48",                                                 
     "@types/node": "^9.4.5",                                                   
     "chai": "^4.1.2",                                                          
     "mocha": "^5.0.0",                                                         
     "should": "^13.2.1",                                                       
     "ts-node": "^4.1.0",                                                       
     "typings": "^2.1.1"                                                        
   }

**Comment by btd** [comment]
that is an issue. see also last comment https://github.com/shouldjs/should.js/issues/147
Use either should or chai, not both.

**Comment by Thavaprakash** [comment]
Thanks @btd , issue is resolved.
