### ISSUE TITLE
Suggestion: extend .equal() with .equal.to() or equalTo()

### ISSUE THREAD

**Issue by robzenn92** [shouldjs/should.js#175]
Hi.
Please, assume that I did not have the chance to inspect the implementation details of this framework..
I am wondering if it is worth to consider (wheter it is possible) to add support for `.to` to improve readability of `Assertion#equal` and similars, as follows: `true.should.be.equal.to(true)`.

Thanks,
Roberto

**Comment by btd** [comment]
Sorry, this just increase number of internal keys to support. For me it does not make any sense to implement.
