### ISSUE TITLE
should.rejected() does not compile in typescript

### ISSUE THREAD

**Issue by lev-kuznetsov** [shouldjs/should.js#176]
Hi.

Answer several questions if it is a bug:

## Node.js version?
Tried 7.10.1, 8.9.4 and 10.3.0

## Should.js version?
13.2.1

## How to reproduce it?
Typescript doesn't compile `.rejected()` or `.fulfilled()` off a `promise.should` such as `Promise.resolve().should.be.fulfilled()`

Here's a repro repo:

https://github.com/lev-kuznetsov/should-promise-typescript-issue

**Comment by btd** [comment]
Sorry for long response, was quite busy at work and home. This was already fixed at master for some time. I just published update with this.
