### ISSUE TITLE
Missing Git tags

### ISSUE THREAD

**Issue by Gaelan** [shouldjs/should.js#179]
Looks like versions 13.2.2 and 13.2.3 are missing git tags.

**Comment by btd** [comment]
Yep, it is manual process. I do not tag it each time as really do not see any benefit.

**Comment by guimard** [comment]
@btd : hello, tags are useful for packagers _(I'm packaging should.js for [Debian](https://www.debian.org/))_: our rules needs a build from source, not from npmjs registry.

Cheers,
Xavier

**Comment by btd** [comment]
@Gaelan @guimard i added missing tags, thanks for explanation
