### ISSUE TITLE
which.is.a.Number().or.is.Null()

### ISSUE THREAD

**Issue by dooleyb1** [shouldjs/should.js#183]
Hi,

Not a bug, just a question. Had a look around in quite a few places for this and couldn't find any examples of what fitted my needs. I was wondering was it possible to do say the following:

`this.obj.should.have.property('status').which.is.a.Number().or.is.Null();`

This is so we can allow for properties that can either be `null` or `x`.

Thanks!

**Comment by btd** [comment]
This question is comming from time to time.
There is no .or assertion helper because in 99% cases i seen it is bad test.
Test must be deterministic and exact. Meaning that if you pass to test the same data you must get the same result. In you case you must 2 tests one for null and other for number
