### ISSUE TITLE
TypeError: should(...).not.exist is not a function

### ISSUE THREAD

**Issue by ks-s-a** [shouldjs/should.js#184]
Hi.

Answer several questions if it is a bug:

## Should.js version?
13.2.1, 13.2.3

## How to reproduce it?
https://runkit.com/embed/t2h1tczvcabr

var should = require("should/as-function")
should(null).not.exist()

I guess it should work and I didn't have any mistake in such tiny piece of code.

**Comment by btd** [comment]
You used it incorrectly. I would suggest to use .Null or just .ok

**Comment by ks-s-a** [comment]
> You used it incorrectly. I would suggest to use .Null or just .ok

But why? I see the method in doc: https://shouldjs.github.io/#should-exist and it should work, don't you? Im my mind the method should check incomming argument for being null or undefined. Where am I wrong?

**Comment by btd** [comment]
> But why? I see the method in doc: https://shouldjs.github.io/#should-exist and it should work, don't you?

See the example at link:

```
should.exist(1);
should.exist(new Date());
```

and your example:
```
should(something).not.exist()
```

See the difference?

**Comment by btd** [comment]
Sorry accidentally press send.

**Comment by ks-s-a** [comment]
Ouch, I see. Thank you for help!

But it's still looks like it would be more obvious to support both options. I see not so big difference between 

```
should(a).be.an.Object()
```

and

```
should(a).not.exist()
```

It looks like a common way to check the variable. Is the current approach more convenient for you? What do you mean?

**Comment by btd** [comment]
This is a bit different things. `should.exist` it is literally `something == null` check. For similar (not exact) behavior you can use `.ok()` assertion (it is just matter of naming things). Or you can check exactly what is returned with `.null()` or `.undefined()`
