### ISSUE TITLE
Should hangs Karma (when using RequireJS?)

### ISSUE THREAD

**Issue by jayboyd** [shouldjs/should.js#25]
For a long time I thought this was a defect with Karma, which was newer to me than Should.js, but the issue finally was resolved when I removed the latter from my project. 

If needed I can revert to older revision to troubleshoot, but I don't have much time for this at moment. The observable behavior was that I would kick off a karma process with file watching, and tests would run fine first time, but when I'd touch files, *most* of the time but not all the time, the tests would not re-run. This seemed to be an issue with karma and OS file-watching, but turned out was immediately resolved by removing Should.js. When this issue occurred, even refreshing the test run browser would refuse to execute, would hang with no output anywhere.

Sounds like a race condition (not 100% of the time, but maybe 90% of the time tests would fail like this), and though I never confirmed this, I highly suspect is specific to using RequireJS as well. Maybe Should.js is being re-initialized in some way, and doesn't play well as it modifies Object.prototype. I then read something that (I guess wrongly?) led me to believe Should.js is suitable for Node code but not expected to work well in browser. 

As I recall, I had tried including 'should' as a framework in karma.conf, and tried giving it a stub: exports: clause. That doesn't seem to be supported. I tried explicitly importing into requirejs test spec modules, which seems to trigger the problem, and then not explicitly, resulting in more obvious race condition where on some runs the tests would fail as should.js had not initialized when they are loaded. 

Hope that helps, I may have more time later to troubleshoot or provide a working example, but my code is not open source so I'd have to spend some time on this that I don't have at the moment.

**Comment by btd** [comment]
I create [examples](https://github.com/shouldjs/examples) repository. One of them how requirejs and should work together. 
I need to say that all problems i had in configuration was from requirejs and karma adapter.
So i close this repo, as there is no any bug.
