### ISSUE TITLE
IE 9

### ISSUE THREAD

**Issue by DylanPiercey** [shouldjs/should.js#32]
Is support going to come back for ie9?

**Comment by btd** [comment]
It is supported with known unfixable bugs.

**Comment by btd** [comment]
So for example you cannot do in IE9:
```
var should = require('should');

10.should.be.greaterThen(0);
```
Because of that bug. But you can do still
```
should(10).be.greaterThen(0);
```
Also any assertion returning number working as expected:
```
({a : 10}).should.have.property('a').eql(10);
```

So affected only one case of creation. When you call .should on Number.

**Comment by dasilvacontin** [comment]
@btd Is it only when calling .should on a Number? Is this this the same reason IE8 is not supported, or breakage is bigger there? Thanks!

**Comment by btd** [comment]
@dasilvacontin yes, affected cases like `(10).should`.
IE8 is not supported because of weak es5 support (at least Object.defineProperty)

**Comment by dasilvacontin** [comment]
@btd I see – thanks much for the answer! :)
