### ISSUE TITLE
Confusing positives for is.a.<anything>

### ISSUE THREAD

**Issue by rhalff** [shouldjs/should.js#35]
I've noticed non-existing matchers will not throw an error.

```
var n = 1;

n.is.a.Number;   // true
n.is.a.number;   // true
n.is.a.anything;  // true
n.is.a.string;      // true
n.is.a.function;  // true

n.is.a.String; // false
n.is.a.Function; // false
```
It can be quite confusing when things seem to match, but in reality they are false.

Is this intended behavior or an artifact?

**Comment by rhalff** [comment]
Nevermind, I see how this is impossible to catch.. :-)

**Comment by btd** [comment]
That is possible to fix partially, when will be available Proxy. I am waiting for iojs 1.0 to test everything.
That was suggested in old repo. I will reopen this to do not forget.

**Comment by btd** [comment]
I will wait when at least 2 browsers implement direct proxy interface.

**Comment by rhalff** [comment]
ok, thanks for considering this.

**Comment by btd** [comment]
I have added to 4.6.0 direct Proxy support, will look for feedback.
