### ISSUE TITLE
.containDeep won't compare null values

### ISSUE THREAD

**Issue by bakavic** [shouldjs/should.js#37]
Given the example:

    var test = {'hi': null};
    test.should.have.property('hi', null); // This passes
    test.should.containDeep({'hi': null}); // However, this throws an assertionError

Should `null` values in JSON objects be considered legit?

The line that affects this : https://github.com/shouldjs/should.js/blob/4.5.1/lib/ext/contain.js#L146
Perhaps the handling for a null use case is unwieldy?

**Comment by btd** [comment]
Yes, i think that was some legacy code for first version of .containDeep.

**Comment by bakavic** [comment]
Awesome! Thanks for the quick resolution!
