### ISSUE TITLE
`should.not.equal(complexObject)` is not optimal

### ISSUE THREAD

**Issue by raymondfeng** [shouldjs/should.js#40]
Assuming we have two complex objects, such as registry1 and registry2, the following assertion becomes very expensive:

registry1.should.not.equal(registry2)

`should` at the moment always asserts the `equal` first, creates an `AssertionError`, and then tests the not condition by catching the error. See https://github.com/shouldjs/should.js/blob/master/lib/assertion.js#L47-L68. For complex objects, the [getMessage](https://github.com/shouldjs/should.js/blob/master/lib/assertion.js#L202-L208) is very expensive (in our case, more than 4 seconds).

The work around is to provide a custom message for the assertion. I wonder if the `assert` could check the `negate` flag and only construct a dummy `AssertionError` if `negate` is `true`?

See https://github.com/strongloop/loopback-datasource-juggler/pull/431

**Comment by btd** [comment]
I understand the issue, If it is not hard is it possible to make for me some example that i can add to tests, while i am working on fix.

**Comment by raymondfeng** [comment]
Sure, I'll add test case.

**Comment by raymondfeng** [comment]
Here we go:

```js
it('should optimize not.equal for complex objects', function() {
    function mockComplexObject(prefix, depth, width) {
      if (depth <= 0) {
        return 'value-' + prefix;
      }
      var obj = {};
      for (var i = 0; i < width; i++) {
        obj[prefix + depth + '_' + i] = mockComplexObject(prefix, depth-1, width);
      }
      return obj;
    }
    var a = mockComplexObject('a', 8, 4);
    var b = mockComplexObject('b', 8, 4);

    a.should.be.not.equal(b); // It takes a while
  });
```

**Comment by btd** [comment]
Please, try 4.6.5. For nested assertions it will not generate messages while not need. Looks not ideal, will refactor this later, but should fix your issue.
Let me know if that works for you.

**Comment by raymondfeng** [comment]
@btd Thanks for the fix!
