### ISSUE TITLE
weird behavior when should set global

### ISSUE THREAD

**Issue by fghibellini** [shouldjs/should.js#41]
Should can't be used when set global in node, example:

    describe("test suite", function() {

        it("this works", function() {

            var should = require("should");

            should(null).eql(null);

        });

        it("why does this throw an error?", function() {

            global.should = require("should");

            should(null).eql(null);

        });

    });

the trhown error is: "TypeError: Property 'should' of object #<Object> is not a function"

**Comment by btd** [comment]
Because shouldjs extends Object.prototype. But `global` is also object, so you call in object global getter `should`. 
To make it really global, you can try use Object.defineProperty:
```
Object.defineProperty(global, 'should', {
value: should
})
```
or you can set it at **first** require of shouldjs
```
global.should = require('should').noConflict();
should.extend();
```

**Comment by fghibellini** [comment]
your solutions work, thanks for the quick answer :).

although since should extends the  Object prototype if i set "should" directly on global, js should first
check on the object itself and then on its prototype when searching for the property "should",
am I wrong ?

**Comment by btd** [comment]
Yes, right with values. But 'should' is a getter without setter, that is why you cannot change it directly.

**Comment by fghibellini** [comment]
thanks for the explanation, I'll lok into it
