### ISSUE TITLE
Nested empty objects are compared as equal by .containDeep

### ISSUE THREAD

**Issue by willfrew** [shouldjs/should.js#42]
Example:

``` javascript
require('should');

var obj = {
  prop: {
    nestedProp1: [],
    nestedProp2: 123
  }
}

obj.should.containDeep({ prop: { nestedProp1: [], nestedProp2: 123 } });
obj.should.containDeep({ prop: { nestedProp1: [] } });
obj.should.containDeep({ prop: { nestedProp2: 123 } });
obj.should.containDeep({ prop: {} }); // Throws an error
```

Prior to version v4.6.4 this would not have thrown an Error and is the behaviour I would expect from .containEql.

I notice that commit 1e498979421fe44fa09cd42ae17970006827ac9c changes this behaviour but I didn't have time to work out if this was the intended change in functionality.

**Comment by btd** [comment]
Yes, that was bug fix for this. If .containDeep* finds that given object do not have keys to check next it will compare given object and passed to assertion to be equal.
To be clear see such examples:
```
obj.should.containDeep({ prop: {} });
//it see object so for each property: prop
{ nestedProp1: [], nestedProp2: 123 }.should.containDeep({}) <-- passed empty object so we try to compare objects for equality, previously if it is missing it feel ok

var d1 = new Date();
var d2 = new Date();
{ d: d1}.should.containDeep({ d: d2 });
d1.should.containDeep(d2);
// dates does not have public properties - so containDeep will check for object equality as you can expect there -> previously we feel ok
```
So to fix that bug i added simple check for empty object. I can add check that it is [object Object] only but this will create more questions then help.
Also that is why (as was several breaking changes, which was actually bug fixes) i bump major version .

I would like to see more opinions on subject, before any further change in this area.
