### ISSUE TITLE
ES6 generator throw assert

### ISSUE THREAD

**Issue by damnhipster** [shouldjs/should.js#44]
The function for the `.should.throw()` assertion doesn't allow for generator functions to be used.
```javascript 
(function * () {
  yield throwsError();
}).should.throw();
```
Instead we have to use the iterator on the generator throwing an error like so:
```javascript
(function () {
  var f = throwsError();
  f.next();
}).should.throw();
```

It would be useful if it could work, like we do for the normal use of the assertion.
```javascript 
(function () {
  throw new Error();
}).should.throw();
```

**Comment by btd** [comment]
Right, idea. Will add this.

**Comment by btd** [comment]
Added. Try 5.1.0. I have added initial support of generators to other methods also.

**Comment by btd** [comment]
If anything still not work, let me know pls - just reopen this issue.

**Comment by damnhipster** [comment]
I'm getting an error message: 
```
AssertionError: expected [object Generator] to be a function
    expected [object Generator] to have type function
        expected 'object' to be 'function'
```
I think it could be [this line of code](https://github.com/shouldjs/should.js/blob/5.1.0/lib/ext/error.js#L42). I don't think you can invoke a generator function fully just by `fn()`. That will just return back an iterator, so you have to either loop through it by calling `iterator.next()`, or doing `yield fn()` (`node --harmony` only).

I'll submit a fix later, but wanted to point out that it may not be working currently.

**Comment by btd** [comment]
@damnhipster can you pls show example?

**Comment by btd** [comment]
> I think it could be this line of code. I don't think you can invoke a generator function fully just by fn().   That will just return back an iterator, so you have to either loop through it by calling iterator.next(), ordoing yield fn() (node --harmony only).

Yes, my idea was to invoke function to get iterator and then call .next.

**Comment by damnhipster** [comment]
Here's a way to reproduce it.
```javascript
var throwsError = function * () { 
  throw new Error(); 
  yield console.log('hello'); 
}

(function * () { 
  yield throwsError() 
}).should.throw()
```

**Comment by btd** [comment]
I could not reproduce it with iojs 1.6.2:
```
$ node -v
v1.6.4
$ node
> var should = require('./')
undefined
> var throwsError = function * () { 
...   throw new Error(); 
...   yield console.log('hello'); 
... }
undefined
> (function * () { 
...   yield throwsError() 
... }).should.throw()
{ obj: [Function],
  anyOne: false,
  negate: false,
  params: { actual: [Function] } }
> 
```

**Comment by damnhipster** [comment]
It seems to be a problem with Node.js 0.11.4.

Node.js 0.12 works fine :smile: 

I did see something else though:

```
> var noError = function * () { yield console.log('no error') }
undefined
> (function * () {yield noError()}).should.throw()
{ obj: [Function],
  anyOne: false,
  negate: false,
  params: { actual: [Function] } }
```
It should throw an `AssertionError` but it seems to work... Is there some error being thrown from the implementation which is being masked by the test?

**Comment by btd** [comment]
Yep, last example looks like a bug.
