### ISSUE TITLE
Asserting array deeply constans object with key

### ISSUE THREAD

**Issue by hellboy81** [shouldjs/should.js#48]
- How to assert that `myArr` contains both `myKey1` and `myKey2`:

 ```js
myArr : [
 {myKey1: [..]}
 {myKey2: [..]}
]
````

- Have you plans to add gitter chat room?

**Comment by btd** [comment]
Hi.
For deep search use `.containDeep` and `.containDeepOrdered`. For your example:
```
$ node
> var should = require('should')
undefined
> var myArr = [ 1, 2, 'abc', { myKey1: [ 1, 2, 3]}, { myKey2: [ 4, 5, 6] }];
undefined
> myArr.should.containDeep([{ myKey1: [] }, {myKey2: []}])
{ obj: [ 1, 2, 'abc', { myKey1: [Object] }, { myKey2: [Object] } ],
  params: { operator: 'to contain [ { myKey1: [] }, { myKey2: [] } ]' },
  negate: false }
> myArr.should.containDeep([{ myKey1: [4] }, {myKey2: []}])
```
Just use empty arrays. If you add any value it begin search deeper.

I can add gitter chat room, but just for me it is a bit easier to answer in issues.

**Comment by hellboy81** [comment]
OK, thanks. We can also speak Russian in chat.
