### ISSUE TITLE
when I click 'new pull request', I'm being redirected to tj/should.js

### ISSUE THREAD

**Issue by kaspars** [shouldjs/should.js#50]

**Comment by btd** [comment]
![2015-03-09 18 59 10](https://cloud.githubusercontent.com/assets/334851/6558656/7f85174e-c68e-11e4-9d9a-22f0c1a28df3.png)
Just choose correct fork. As this repository is a fork, github choose default base fork.

**Comment by kaspars** [comment]
oh, right, wasn't familiar with that. sorry for the noise.
