### ISSUE TITLE
"123".should.not.exist is not failing as expected

### ISSUE THREAD

**Issue by ryedin** [shouldjs/should.js#57]
I'm using mocha 2.2.4 and should 5.2.0.

Any `should.not.exist` assertion is always passing no matter what.

**Comment by ryedin** [comment]
OK, so this may be a non-issue / misunderstanding. 

`should.not.exist("123")` works, but `"123".should.not.exist` does not.

Leaving it open in case the `"123".should.not.exist` is _supposed_ to be working. I assumed all assertions worked either way and I like the Object extension syntax better so that's what I was using.

**Comment by btd** [comment]
There is no [.should.exist](http://shouldjs.github.io/#should-exist) (and never was). Form of property call really does not make any sense, because in all relevant cases when it will be usefull it will not work:
```
null.should.not.exist;//not work
undefined.should.not.exists;//not work

// all other cases will work (which has prototype of cause), but does not make any sense if above 2 does not work.
```

**Comment by ryedin** [comment]
Heh, yeah ok, now that I think of it more I see where my brain was failing me :)
