### ISSUE TITLE
Strange behavior with equal

### ISSUE THREAD

**Issue by GM-Alex** [shouldjs/should.js#58]
If I use 

```javascript
body.should.be.equal({response: 'ok'});
```

to test if a response returns the right content, the test fails because it says the result is not identical, but they are. Here is the error:

``
AssertionError: expected { response: 'ok' } to be { response: 'ok' }
``

And here the expected 

```json
{
  "response": "ok"
}
```

and the given return value

```json
{
  "response": "ok"
}
```

Which are obviously the same.

**Comment by btd** [comment]
[.equal inside it is ===](http://shouldjs.github.io/#assertion-equal), which of cause will not work for deep comparison. You need to use .eql there which do deep comparison.

**Comment by GM-Alex** [comment]
@btd Didn't notice that. Many thanks for your help.
