### ISSUE TITLE
Exceptions Entering Console Output on .should.throw();

### ISSUE THREAD

**Issue by andrewvaughan** [shouldjs/should.js#59]
Just upgraded to 6.0.0 and now all of my `.should.throw()` blocks are printing the exception out in the log - this didn't happen with 5.x.x.

**Comment by btd** [comment]
Can you show example, pls?

**Comment by btd** [comment]
Got issue, will fix in 5 min. Sorry silly mistake. Hope one time i will do major release without patches in the same day.

**Comment by btd** [comment]
Just pushed 6.0.1. Sorry again, it was silly.

**Comment by andrewvaughan** [comment]
Quick fix!  Thank you.
