### ISSUE TITLE
.empty not working when using should as a method

### ISSUE THREAD

**Issue by ghusse** [shouldjs/should.js#62]
Hello,

I'm trying to upgrade to the latest version of should.js. I'm using should after deleting `Object.prototype.should`, because some of my object does have a property named `should` (and I cannot change that).

I experienced an issue on calls like this one:
```
should('foo').not.be.empty;
```

I got an error `and I experienced an issue on calls like this one: `Cannot read property 'have' of undefined` which is caused by should.js

I re-created the issue in a unit test here: https://github.com/ghusse/should.js/commit/6ff8d36a28667d088320c7f34bc63479286b244b

If you run NPM test with this new test case, you get this error:

```
1) should as a method should correctly detect empty strings
   
       Cannot read property 'have' of undefined
       
       + expected - actual
       
       
       at Assertion.<anonymous> (lib/ext/property.js:272:22)
       
       271 |     if(util.length(this.obj) !== void 0) {
       272 |       this.obj.should.have.property('length', 0);
       273 |     } else {
       
       at Assertion.prop.(anonymous function) [as empty] (lib/assertion.js:51:12)
       
       50 |     try {
       51 |       func.apply(context, arguments);
       52 |     } catch(e) {
       
       at Context.emptyTest (test/ext/method.test.js:21:16)
       
       20 | function emptyTest(){
       21 |   should('').be.empty;
       22 |   should('foo').no.be.empty;
       
npm ERR! Test failed.  See above for more details.
```

**Comment by btd** [comment]
Yes, correct. It is a bug. Will fix today, probably in hour or two

**Comment by btd** [comment]
Just published 6.0.2, pls give it a try. I replaced all getter usage of should with function calls, so every supplied assertion should work without getter.

**Comment by ghusse** [comment]
Thank you for your quick reply.

I merged your modifications into my branch and re-launched the tests, but I get the same error.

You can try locally with this branch: https://github.com/ghusse/should.js/tree/empty-not-working

output:

```1) should as a method should correctly detect empty strings
   
       Cannot read property 'have' of undefined
       
       + expected - actual
       
       
       at Assertion.<anonymous> (lib/ext/property.js:272:22)
       
       271 |     if(util.length(this.obj) !== void 0) {
       272 |       this.obj.should.have.property('length', 0);
       273 |     } else {
       
       at Assertion.prop.(anonymous function) [as empty] (lib/assertion.js:51:12)
       
       50 |     try {
       51 |       func.apply(context, arguments);
       52 |     } catch(e) {
       
       at Context.emptyTest (test/ext/method.test.js:21:16)
       
       20 | function emptyTest(){
       21 |   should('').be.empty;
       22 |   should('foo').no.be.empty;
```

**Comment by btd** [comment]
Ok, will look on your branch.

**Comment by ghusse** [comment]
Indeed, this line causes the issue:

```
this.obj.should.have.property('length', 0);
```

**Comment by btd** [comment]
Yep, just found also. I miss one line.

**Comment by btd** [comment]
Just did 6.0.3. Should be last. Sorry for this.

**Comment by ghusse** [comment]
Thanks, it works now.
