### ISSUE TITLE
matchAny and matchEach are inconsistent

### ISSUE THREAD

**Issue by dpatti** [shouldjs/should.js#65]
`match` treats objects specially and looks to see that all keys and values of the provided object match the subject. `matchEach` and `matchAll` use simple equality for objects. In general, I would expect all forms of `match` to follow the same rules. This seems like a missed opportunity, but perhaps you have a better reason for creating it this way. Example:

```javascript
({ a: 1, b: 2 }).should.match({ a: 1 }); // pass
[{ a: 1, b: 2 }].should.matchEach({ a: 1 }); // fail: expected [ { a: 1, b: 2 } ] to match each { a: 1 }
```

Of course, this would break compatibility.

And while we're on the subject, I'd say that `matchSome` and `matchEvery` are more idiomatic javascript given `Array#some` and `Array#every`.

**Comment by btd** [comment]
Well, i mostly agree with you. Adding just aliases will not break anything. Need to test how many tests will be broken when use .match for elements check. Anyway there is one more breaking issue pending, so it is ok if this one will be breaking.

**Comment by btd** [comment]
@dpatti it was fixed in 7.x, if you still interested.

**Comment by dpatti** [comment]
@btd Awesome! Thanks so much.

**Comment by btd** [comment]
@dpatti take a look in upgrading instructions, if you want update current code. There was a lot of breaking changes.
