### ISSUE TITLE
Regex matching

### ISSUE THREAD

**Issue by silenceisgolden** [shouldjs/should.js#67]
`'{%layout\'main\'%}'.should.match(/\{\%[\s]*?layout[\s]*?[\"|\']([\S]+?)[\"|\'][\s]*?\%\}/g)` fails but
`'{%layout\'main\'%}'.match(/\{\%[\s]*?layout[\s]*?[\"|\']([\S]+?)[\"|\'][\s]*?\%\}/g)` succeeds and returns the right string

Example http://regexr.com/3b6hg

**Comment by btd** [comment]
I cannot reproduce with several versions and master. Which versions do you use?

**Comment by btd** [comment]
@silenceisgolden i will close this issue as i cannot reproduce it still, and you do not provide me anything more info. Feel free to reopen or open new issue if you need.
