### ISSUE TITLE
Set equivalence

### ISSUE THREAD

**Issue by fatuhoku** [shouldjs/should.js#68]
`[3,2,1].should.???.[1,2,3]` ???

This is very common and very useful me.

**Comment by fatuhoku** [comment]
My workaround at the minute is to do

```js
            test.should(keywords).containDeep(expected);
            test.should(expected).containDeep(keywords);
```

**Comment by btd** [comment]
There is no direct assertion for what you need. But you did it right with `.containDeep` for 2 arrays it works in most cases as you expected.
Also you can do simple trick:
```js
var should = require('should');

var a1 = [1, 2, 3];
var a2 = [3, 2, 1];

a1.sort().should.be.eql(a2.sort());
```

**Comment by btd** [comment]
Also just from curiosity what is `test` variable in your example?

**Comment by fatuhoku** [comment]
@btd Ah. `test.` is from http://unitjs.com. It's a bundle of useful testing frameworks. That's how I found shouldjs in the first place.

I guess sorting would work for my use-case, because I'm using strings.
