### ISSUE TITLE
Array Assertion returning function

### ISSUE THREAD

**Issue by timmckenzie** [shouldjs/should.js#69]
Looks like there is a big regression with the Array assertion.  

In version **7.0.0** and newer the example code below will return:
```
should Array returned a function
should Array() returned a object
```

In version **6.0.3** the example code will return:
```
should Array returned a object
TypeError: Property 'Array' of object #<Assertion> is not a function 
```

**Repro code** I get the the same results in Node 0.10, 0.12, and iojs v2.3
```javascript
require('should');
var arr = [1, 2, 3];

console.log('should.Array returned a ' + typeof arr.should.be.Array);
console.log('should.Array() returned a ' + typeof arr.should.be.Array());
```

I think that the behaviour in version 6 is correct, but looking at the tests they are using the Array() syntax.  

Is this a bug?  Which syntax is correct? Did this change get missed in history.md?  http://shouldjs.github.io shows Array being used without calling it as a function, but I find that a little unclear.  

I did not check any of the other type checks to see if the behaviour changed.

Thanks.

**Comment by btd** [comment]
Hello.

It is one of breaking changes in 7.x release. In history.md lines 16-17:
```
Breaking Change No more getter assertions. No all assertions are functions.
Breaking Change No more proxy returning, to check property names.
```

In wiki page about [breaking changes](https://github.com/shouldjs/should.js/wiki/Breaking-changes) item 1.

In short at 7.x i dropped getter assertions to be real functions, to remove any possiblity for false positive result when using wrong name of assertion (simply typo).

In your example: .Array it is a function, when call it .Array() returns Assertion object instance (simply this).

About docs, yes it is bug. There are missing parenthesis in method titles.

**Comment by timmckenzie** [comment]
Ok. I did not look in the wiki.  
Thanks!

**Comment by btd** [comment]
I will reopen it, to do not forget fix docs.

**Comment by btd** [comment]
Fixed all docs. Not sure why it was not uploaded, locally i had fixed version.
