### ISSUE TITLE
A little mistake on `http://shouldjs.github.io/#assertion-below`

### ISSUE THREAD

**Issue by JerryC8080** [shouldjs/should.js#71]
just a little mistake ..... on here [http://shouldjs.github.io/#assertion-below](http://shouldjs.github.io/#assertion-below)

![3 pic](https://cloud.githubusercontent.com/assets/6801672/8888736/aebfdd6c-32ec-11e5-8122-3a9d34ab68c4.jpg)

**Comment by btd** [comment]
Yep, it is because of https://github.com/shouldjs/should.js/blob/master/lib/ext/number.js#L112, you did PR for docs repo, right?

**Comment by JerryC8080** [comment]
@btd  
What does PR mean?
I just starting use should.js and take an overview of its docs，and then found this little mistake.

**Comment by JerryC8080** [comment]
By the way, did you use something to translate annotations to docs？?
Would you might to tell me what it is? 
This cause my interest.

**Comment by btd** [comment]
@JerryC8080 PR - it is Pull Request. Yesteday was pull request to docs repo to fix the same mistake (i thought it was you).
I am using custom [dox](https://www.npmjs.com/package/dox), with similar template that lodash uses.

**Comment by JerryC8080** [comment]
hahahhhh, what a coincidence。
And thank you , i will take a look of dox
