### ISSUE TITLE
should.exist() and should.not.exist() doesn't work!!

### ISSUE THREAD

**Issue by jaedoochoi** [shouldjs/should.js#72]
```
describe('Testing the save method', function () {
       it('Should be able to save without problems', function () {
           article.save(function (err) {
               should.exist(err);  //err is null but success!
           });
       });

        it('Should not be able to save an article without a title', function () {
            article.title = '';

            article.save(function (err) {
                should.not.exist(err); //err is occur but success!! 
            });
        });
   });
```
What is the problem!! Please help me~

**Comment by btd** [comment]
Could you add more information, from your description it is unclear what exactly problem you have. 
In first case err is null, right? and you check with should.exists that it is not null - that is first problem.
In second case all the same but opposite.

**Comment by jaedoochoi** [comment]
Exactly right! I can't understand that why are they pass the shouldjs test. 
1. err is null but test pass
2. err is not null but test pass.
Could you explain me what is wrong?

**Comment by btd** [comment]
should.exists literally check that given object is not null, you need to swap your checks. First should check should.not.exist(err) because it is null this will pass, second should be should.exist(err) because err in second case is not null
