### ISSUE TITLE
empty 

### ISSUE THREAD

**Issue by r3dlin3** [shouldjs/should.js#75]
Hi,

I'm trying to test that my array is not empty.
The following does not trigger an error
```
[].should.not.be.empty; 
```
For the time being, I'm using a workaround:
```
[].length.should.be.above(0);
```
I'm using version 7.0.3

**Comment by btd** [comment]
Hello.
should.js since version 7.x have no getter assertion. So your example should look like:
```js
[].should.not.be.empty(); 
```
