### ISSUE TITLE
Matching against an object can throw TypeError and break .matchAny

### ISSUE THREAD

**Issue by enicholson** [shouldjs/should.js#76]
Using 7.0.3:

```javascript

require('should');

{}.should.match({prop:'foo'});   //throws AssertionError, perfect

{}.should.match( {nested: {prop:'foo'} } ); //throws TypeError, not great

[{nested:{prop:'foo'}}, {}].should.matchAny({nested:{prop:'foo'}}); //Success

[{}, {nested:{prop:'foo'}}].should.matchAny( {nested: {prop:'foo'}} ); //throws TypeError, should be success

```
This last case is the most troublesome.  Getting a TypeError on a ```match``` isn't too bad because your test still fails where it should.  But ```matchAny``` doesn't work as expected.

**Comment by btd** [comment]
It should be fixed in 7.0.4.
Reason why last line failed the same because second failed. It should throw now AssertionError in second case and pass last. Let me know if it works.
