### ISSUE TITLE
should.exist not working w/ empty string

### ISSUE THREAD

**Issue by iamdevonbutler** [shouldjs/should.js#78]
Hey,
I can't get the following to work properly:

should.exist(res.body.state) // res.body.state === ''

I get: "Uncaught TypeError: undefined is not a function"

What am I doing wrong?

**Comment by btd** [comment]
You example looks correct:
```
$ node
> var should = require('.');
undefined
> var res = { body: { state: 'something' }};
undefined
> should.exist(res.body.state);
undefined
> should.exist(null);
AssertionError: expected null to exist
```

Could you add more details? Full reproducible example most appreciated.

**Comment by iamdevonbutler** [comment]
Sure,

I am using coffeescript, mocha, supertest and should:
  
  id = null
  
  # works
  beforeEach (done) ->
    postdata =
      displayName: 'jay'
      email: 'jpescione@gmail.com'
      password: 'password'
    supertest('http://localhost:4000')
      .post('/api/v1/users/create')
      .send(postdata)
      .expect 200, (err, res) ->
        id = res.body.userId
        should.be.ok id
        done()

  it 'should return a user object given a valid user ID', (done) ->
    supertest('http://localhost:4000')
      .get('/api/v1/users/get/'+{id})
      .expect 200, (err, res) ->
       #res.body = { email: 'jpescione@gmail.com', displayName: 'jay', password: 'hash', gender: '' }
        should.be.ok res.body # works
        should.be.ok res.body.displayName # works
        should.be.ok res.body.email # works
        should.exist res.body.gender # does not work
        done()

**Comment by iamdevonbutler** [comment]
may be an edge case w/ the coffeescript - if it is nbd - i have a workaround but wanted to report the issue anyway.

**Comment by btd** [comment]
Actually about your usage of `should.be.ok id` i am not sure about coffescript, but if it is translated to `should.be.ok(id)` then it did nothing actually. You can call it like `should(id).be.ok`. The same other places. So it looks like because of wrong usage you got false positive and last line not works, but it is single written right =).

**Comment by iamdevonbutler** [comment]
still couldn't get it to work.

If no one else is having issues w/ this i say close it out as there are other ways to write that assertion.

**Comment by btd** [comment]
If you want to close, feel free. If you need help, i am ok to help. Can you post your test and data you are getting.
