### ISSUE TITLE
.empty on empty array hangs forever

### ISSUE THREAD

**Issue by akotranza** [shouldjs/should.js#79]
// hangs forever
emptyarray.should.have.lengthOf(0);
done();

// works fine
emptyarray.should.be.empty;
done();

**Comment by btd** [comment]
`emptyarray.should.be.empty;` it should be `emptyarray.should.be.empty();`

**Comment by btd** [comment]
Could you post full example?

**Comment by akotranza** [comment]
Oops, not an issue with should, sorry about that. Finding out that testing promises with mocha is a bit of a mess. Any assert within then(...) was causing mocha to hang forever... forgetting the () on empty was the trick to making it seem like it worked ;)

**Comment by btd** [comment]
Yep, take a look on [examples](https://github.com/shouldjs/should.js/wiki/FAQ#when-testing-with-async-calls-promises-callbacks-etc)

**Comment by akotranza** [comment]
Thanks and yeah I was following the 'correct way with latest mocha' example. The problem was with trying to test "do X then do Y" behavior where X and Y are both async methods returning promises, failing tests were hanging... not "forever" but just timing out (well the timeout was long so it felt like forever).  I'm working around it by pulling out the "do X" into a before(), but that feels hacky.

I'm probably missing something to make this work as expected, but I can live with it for now. Thanks for your replies!

**Comment by btd** [comment]
If i understand correct. You have something like:
```
function returnPromise1() {
   return Promise.resolve(10);
}

function returnPromise2() {
   return Promise.resolve(10);
}

// you can try
it('should test in order', function() {
  return returnPromise1()
    .then(function() {
       return returnPromise2();
    })
})

//or in case you do not need order
it('should test does not matter in which order', function() {
  return Promise.all([
    returnPromise1(),
    returnPromise2()
  ])
})
```

Also maybe tests from [should-promised](https://github.com/shouldjs/promised/blob/master/test/promised.test.js) can help.

**Comment by akotranza** [comment]
Thanks, the ordered example is exactly what I was doing, with the promises coming from Sequelize. If the test fails it's just unexpectedly slow, seemingly unrelated to the timeout value. If I move the first promise to an async before, failed tests fail faster. As far as I can tell the only difference is the speed at which the test fails. (Which is OK for me now that I think I understand it better).

**Comment by akotranza** [comment]
this is a poor example because the db population could just as well go in the suite setup function

```javascript
    describe('the slow way', function() {
      it('is oddly slow but the result is as expected', function() {
        return SomeSequelizeModel.bulkCreate(someJsonArray).then(function() {
          return SomeSequelizeModel.findAll({}).then(function(rows) {
            should.exist(rows);
            rows.should.be.an.Array;
            rows.should.have.lengthOf(someJsonArray.length);
          });
        });
      });
    });
```

**Comment by btd** [comment]
Yes, that mostly looks correct. You forgot () near .Array, also you can short it a bit (but that is matter of taste):
```js
    describe('the slow way', function() {
      it('is oddly slow but the result is as expected', function() {
        return SomeSequelizeModel.bulkCreate(someJsonArray)
              .then(function() {
                   return SomeSequelizeModel.findAll({})
              })
             .then(function(rows) {
                should(rows).be.ok.and.be.an.Array().with.lengthOf(someJsonArray.length);
             });
      });
    });
```
