### ISSUE TITLE
how to update to 7.0.x without false positives?

### ISSUE THREAD

**Issue by yeahoffline** [shouldjs/should.js#80]
> No more getter assertions. No more false positives tests. No more compains of linters about unused expressions To update existing code you will need to add () everywhere where was getter used. Previous attempt results to fix the false positives were removed.

i have thousands of tests like:

> a.should.be.string;

how should i update? 
A deprecation warning would be nice?

**Comment by btd** [comment]
I used simple regexp matching and a linter to find 'useless' rows. Then just reviewed commit diff. For all I spend 15-20 min.

**Comment by yeahoffline** [comment]
great....

thanks

**Comment by btd** [comment]
usually it is bad idea to update test libs. It could make sense in case you have used linter and you disabled rule for unused expressions.
