### ISSUE TITLE
Object successfully matches a regex

### ISSUE THREAD

**Issue by dpatti** [shouldjs/should.js#83]
The following:

``` js
should({}).match(/regex/)
```

returns without throwing. I am guessing that because the subject is of type object, `should` tries to match the regex _object_, which works because it has no keys. On the downside, if you write `myString.should.match(/regex/)` and `myString` is actually an object, it will always pass, which can lead to mistakes.

To give a more realistic example (and the one that almost bit me):

``` js
new Error("test").should.match(/some expected error message/)
```

**Comment by btd** [comment]
Yep, totally right. But I am not sure if i should consider this bug fix or brecking change?

**Comment by btd** [comment]
Actually i noticed that i covered this case in jsdocs (and api docs):
```
//   * If `other` is a regexp and given object is an object check values on matching regexp
```
but again i agree that it is a bit unclear.

**Comment by btd** [comment]
Well, actually i think it is right idea to chain type check there:
```js
should({}).be.an.Object().and.not.empty().and.match(/regex/);
```
```js
myString.should.be.a.String().and.match(/regex/);
```
Example with error a bit more interesting, you expected that object will be converted to string, but in .match case it checks object keys, but Error's name and message properties by default is not enumerable and thus `Object.keys(new Error('ab'))` will return empty array. So i would change your check:
```js
new Error("test").should.match({ message: /some expected error message/ })
```
I now think need to add more examples and description to docs. Thoughts?

**Comment by dpatti** [comment]
Oh, you're right. I should have checked the documentation, sorry! I definitely just used it wrong. In my mind, I was trying to use the same signature of `.throw()` or `.rejectedWith()` because those are so common to me, but I was in a situation where I had an error object value given and not one thrown or rejected.

I think closing with "working as expected" is merited in this case. In the future, it might be possible to eliminate confusion with removing those regex cases from `match` and forcing users to use `matchEvery` or `matchSome` instead, which feel more relevant because they already have those iterative properties and work on arrays and object values.

**Comment by btd** [comment]
Yes, that is right about iterative nature of .match (i wrote it before .matchEvery and .matchSome). I will add more clear description and examples to jsdoc.
