### ISSUE TITLE
"and" not working anymore in v7*

### ISSUE THREAD

**Issue by co2-git** [shouldjs/should.js#84]
Hey there,

chaining with `and` does not work anymore in 7.1.0:

`parse.should.be.an.Object.and.have.property('type')`

throws error "can not read property have of undefined"

works fine with v6.0.3

cheers

**Comment by btd** [comment]
`.Object()`

You forgot brackets.

17 Сен 2015 г. 7:51 пользователь "co2" <notifications@github.com> написал:

**Comment by co2-git** [comment]
Gotcha! Thanks!
