### ISSUE TITLE
should.be.a.Boolean seems to match objects, strings and numbers

### ISSUE THREAD

**Issue by imran-uk** [shouldjs/should.js#85]
Given code like this:

`var config  = {
  frobnicate: true
}`

Where `typeof(config.frobnicate)` produces `boolean`

These assertions seem to return "truthy" value:

`config.frobnicate.should.be.an.Object`
`config.frobnicate.should.be.a.String`
`config.frobnicate.should.be.a.Number`

When they should return "falsy"

**Comment by btd** [comment]
You forgot brackets `.Object()` etc
