### ISSUE TITLE
Global requirement is different from local

### ISSUE THREAD

**Issue by qt911025** [shouldjs/should.js#86]
Under some circumstances I need to assign `should` to global. Such as

* setup.js
```javascript
'use strict';
global.should = require('should');
```

* test.js
```javascript
'use strict';
require('./setup.js');
should.exist({});
```

However there are no method called `exist`, unlike local requirement of `should`. Is it a bug?

**Comment by btd** [comment]
Hello.

It is known behaviour (when you require should.js it adds getter to Object.prototype and you cannot easy change getter). See [FAQ entry](https://github.com/shouldjs/should.js/wiki/FAQ#use-should-as-global-function) about it.

**Comment by qt911025** [comment]
Got it. Thx.
