### ISSUE TITLE
No Promise() check

### ISSUE THREAD

**Issue by oravecz** [shouldjs/should.js#88]
For some reason, I am not able to access Promise(). I'm using the latest version at the time of this writing.

```
$ npm show should | grep version
  version: '7.1.1',
```

If I dump out the properties of the should() function, I see these properties, but no Promise().

```
$ node
> var should = require('should')
> for (var p in should("")) console.log(p)
a
above
aboveOrEqual
an
and
any
anyOne
approximately
Arguments
arguments
Array
assert
be
below
belowOrEqual
Boolean
class
Class
constructor
containDeep
containDeepOrdered
containEql
deepEqual
empty
endWith
enumerable
enumerables
eql
equal
equalOneOf
Error
exactly
fail
False
false
Function
generator
greaterThan
greaterThanOrEqual
has
hasOwnProperty
have
Infinity
instanceOf
instanceof
is
it
iterable
iterator
key
keys
length
lengthOf
lessThan
lessThanOrEqual
match
matchAny
matchEach
matchEvery
matchSome
NaN
negate
not
null
Null
Number
obj
Object
of
ok
oneOf
ownProperty
params
properties
property
propertyByPath
propertyWithDescriptor
startWith
String
the
throw
throwError
true
True
type
Undefined
undefined
which
with
within
```

**Comment by btd** [comment]
Hi. You need to install and require should-promised.
27 Ноя 2015 г. 3:36 пользователь "Jim Cook" <notifications@github.com>
написал:
>
> For some reason, I am not able to access Promise(). I'm using the latest
version at the time of this writing.
>
> $ npm show should | grep version
>   version: '7.1.1',
>
> If I dump out the properties of the should() function, I see these
properties, but no Promise().

**Comment by oravecz** [comment]
Yes, not sure how I missed that in the api-docs. Guess I just assumed it was stock because the API docs are all together. Thank you.

**Comment by btd** [comment]
I will close this as it is now a part of main repo
