### ISSUE TITLE
Matching nested property against undefined/null property throws TypeError, breaks matchAny

### ISSUE THREAD

**Issue by enicholson** [shouldjs/should.js#89]
This is very closely related to https://github.com/shouldjs/should.js/issues/76
The additional problem is that it fails on "undefined" or "null" properties (where missing properties have already been fixed):

```
//Throws TypeError, should be AssertionError
({nested:null}).should.match( {nested: {prop:/foo/}} );  

//Throws TypeError, should be successful
[{nested:undefined}, {nested:{prop:'foo'}}].should.matchAny( {nested: {prop:/foo/}} ); 
```

**Comment by btd** [comment]
Yep, you are right, it is the same bug. 
I just published 8.0.1. It should be fixed now.
