### ISSUE TITLE
Questions about or property for chaining

### ISSUE THREAD

**Issue by killmenot** [shouldjs/should.js#90]
Hi folks,

In my tests I expect 2 kind of values: number or null, so I'd like to have something similar
```
(task.matter_id === null).should.be.ok().or.a.Number();
```
However, `or` is not defined in should.js. So the questions is how do you handle such situation?
P.S. I found only this on Stackoverflow  - http://stackoverflow.com/a/29622958/1468491

**Comment by btd** [comment]
Well, it is not supported in should.js (and as i know at any assertion lib i know). There is actual reason for this. Your test should be deterministic and test exact behaviour. That actually means in your test you should test that some calls result to be a Number and second test another set of calls results a null.

**Comment by killmenot** [comment]
Yeah, I see this point and I agree with you that your scenario is the correct one (first and second tests for different returned values). However, in my tests I do not need it so I use simple `if`. (even if I know the correct returned value)

```javascript
if (task.matter_id) task.matter_id.should.be.not.equal(2);
```

Anyway, thank you!
