### ISSUE TITLE
Documentation for deepEqual is misleading

### ISSUE THREAD

**Issue by mrtbld** [shouldjs/should.js#91]
The documentation for `should.deepEqual` shouldn't state that it's node.js `assert.deepEqual`. The implementation is from [shouldjs/equal](https://github.com/shouldjs/equal/blob/master/index.js#L39): a deep strict comparison that doesn't behave like node's `deepEqual` (strict vs non-strict), and not exactly like node's `deepStrictEqual`. For instance:

```js
> should.deepEqual(+0, -0)
AssertionError: expected 0 deepEqual -0
> assert.deepEqual(+0, -0)
undefined
> assert.deepStrictEqual(+0, -0)
undefined
```

This also applies to `should.notDeepEqual`.

**Comment by btd** [comment]
Yep, that is true. I will fix docs.

**Comment by btd** [comment]
Updated

**Comment by williamkapke** [comment]
Also: Node's impl only considers enumerable properties.

```javascript
function test() {
  this.b = 987;
}
test.prototype.a = 999;

var t1 = new test();
Object.defineProperty(t1, 'a', { value:123 });
```

```
> t1.hasOwnProperty('a')
true
> t1.propertyIsEnumerable('a')
false
> assert.deepEqual(t1, {b:987})
undefined
> should.deepEqual(t1, {b:987})
AssertionError: expected test { b: 987 } deepEqual Object { b: 987 }
```

**Comment by btd** [comment]
Format function can accept function to extract property names from object (https://github.com/shouldjs/format/blob/master/index.js#L17).
But it seems that is bug that default values inconsistent between format and equal.

**Comment by btd** [comment]
I just did test with should-equal directly:
```
$ node
> var eq = require('should-equal');
undefined
> function test() {
...   this.b = 987;
... }
undefined
> var t1 = new test();
undefined
> Object.defineProperty(t1, 'a', { value:123 });
test { b: 987 }
> eq(t1, { b: 987 })
{ result: false,
  path: [],
  reason: 'A and B have different prototypes',
  a: test { b: 987 },
  b: { b: 987 },
  showReason: true }
>
```
So there is not bug there.

**Comment by williamkapke** [comment]
Yup. I was just wanted to highlight another difference. If the error mentioned the constructor difference that would be perfect.

**Comment by btd** [comment]
@williamkapke it is exactly like you said - difference only in constructor, see:
```
$ node
> var eq = require('should-equal');
undefined
> function test() {
...   this.b = 987;
... }
undefined
>
> var t1 = new test();
undefined
> eq(t1, {b:987})
{ result: false,
  path: [],
  reason: 'A and B have different prototypes',
  a: test { b: 987 },
  b: { b: 987 },
  showReason: true }
>

```
another try:
```
> var a = { b: 987 }
undefined
> eq(a, {b:987})
{ result: true }
> Object.defineProperty(a, 'a', { value:123 });
{ b: 987 }
> eq(a, {b:987})
{ result: true }
>

```
So as i said at last time only difference is a constructors.
