### ISSUE TITLE
'finally': Tests against promises always pass.

### ISSUE THREAD

**Issue by jmhwang7** [shouldjs/should.js#92]
Using `should` version 8.0.2 and `q` version 1.4.1, this test passes when it should fail:

```
it("should fail, because it doesn't resolve to the right number", function () {
      var deferred = Q.defer();
      deferred.promise.should.finally.be.exactly(5);
      deferred.resolve(3);
});
```

**Comment by btd** [comment]
your promise is not evaluated. If we are talking about mocha, you need return promise (or use callback), like:
```
it("should fail, because it doesn't resolve to the right number", function () {
  var deferred = Q.defer();
  var p = deferred.promise.should.finally.be.exactly(5);
  deferred.resolve(3);
  return p;
});
```

This test now fail:
![2015-12-24 10 28 15](https://cloud.githubusercontent.com/assets/334851/11991239/0f5436f6-aa29-11e5-8d4a-bd619a1cd5e0.png)

**Comment by jmhwang7** [comment]
Thank you for your help and quick response! I was stuck for a while on this.

**Comment by btd** [comment]
No problem. You are welcome.
