### ISSUE TITLE
Breaking Changes for 8.x

### ISSUE THREAD

**Issue by bigethan** [shouldjs/should.js#93]
Thanks so much for this library, it's great.  My package updating OCD is itching to update this package, but the wiki doesn't list any breaking changes for 8.x: https://github.com/shouldjs/should.js/wiki/Breaking-changes.  Is that due to oversight, or a lack of breaking changes? Any rough indication on how difficult the upgrade would be would be greatly appreciated.

Thanks again, and happy new year!

**Comment by btd** [comment]
hello. Yep i forgot to fill it, sry.
In 8.x i have not added a lot of breaking changes. You can take a look now.
You can also look at History.md file which i fill for each release.

**Comment by bigethan** [comment]
Awesome thanks!
