### ISSUE TITLE
deepEqual throws for 0 === -0

### ISSUE THREAD

**Issue by VinGarcia** [shouldjs/should.js#99]
I believe that this behavior is not intended, if it is, please mark this as resolved.

When using should to compare 0 and -0 it throws an error when using `eql` or `equal`:

```javascript
require(should)
(0).should.be.exactly(-0) // works
(0 === -0).should.be.true() // works
(0).should.eql(-0) // throws AssertionError: expected 0 to equal -0
(0).should.equal(0) // also throws
```

It also throws with deep comparisons:
```javascript
({ 'a' : [ [ [ 0 ] ] ] }).should.eql({ 'a' : [ [ [ -0 ] ] ] })
```

Tested on 81e052a

**Comment by btd** [comment]
Hi. That is really intended for .eql implementation. And all methods using
it.
That maybe very confusing, but if js have -0  and 0 should be way to
compare them.

23 Янв 2016 г. 18:27 пользователь "Vinícius Garcia" <
notifications@github.com> написал:
>
> I believe that this behavior is not intended, if it is, please mark this
as resolved.
>
> When using should to compare 0 and -0 it throws an error when using eql
or equal:

**Comment by VinGarcia** [comment]
Is there a work around, if I want 0 to eql(0)?

Because I am working with vectors (with sylvester.js), and sometimes they return -0 instead of 0.

I already found a way around but it's not very clean.

**Comment by btd** [comment]
Sorry. There is no easy way. Only if your override .eql yourself.
You can copy Assertion.prototype.eql and use Assertion.add to check first
for zeros and call old .eql. probably right idea to add setting to
should.config like with prototypes equality. I am going to add it tomorrow.
So you can wait for tomorrow.
WDYT?
23 Янв 2016 г. 18:53 пользователь "Vinícius Garcia" <
notifications@github.com> написал:

**Comment by VinGarcia** [comment]
I think it's good. I can wait, thank you!

**Comment by btd** [comment]
Hi, there added `should.config.plusZeroAndMinusZeroEqual`, like:
```
$ node
> var should = require('.')
undefined
> (-0).should.eql(0)
AssertionError: expected -0 to equal 0
    ...
> should.config.plusZeroAndMinusZeroEqual = true
true
> (-0).should.eql(0)
Assertion { ... }
> 

```

**Comment by VinGarcia** [comment]
It seems perfect for me.

If I use it as `should = require('should/as-function')`

Can I still access `should.config`?

**Comment by VinGarcia** [comment]
But I found some problems accessing it

```javascript
> // using nodejs interpreter
> should = require('.')
> should.config
undefined
> var should = require('.')
{ checkProtoEql: false, getFormatter: [Function] }
```
I noticed that if i use var should = require('.') it works, but I wasn't expecting it.

also:

```javascript
> should.config.plusZeroAndMinusZeroEqual = true
> (-0).should.eql(0)
AssertionError: expected -0 to equal 0
```

**Comment by btd** [comment]
Results for `require('should')` and `require('should/as-function')` the same - literally they return the same function.
This option not shown in `should.config` because by default it is assumed `false` so i did not added it manually. 
Make sure you did `npm i` because all changes were done in `should-equal`.

**Comment by VinGarcia** [comment]
Oh yeah it is working fine now, I needed to update should-equal.

Thank you btd, I'll close this issue as solved!

**Comment by btd** [comment]
:+1:

**Comment by VinGarcia** [comment]
Hi @btd, thank you for this, it helped me in about 1/3 of my total tests, and I hope I'm not taking too much of your time.

But I detected a bug when using this new configuration:

```javascript
> var should = require('should')

>should([2,2,0]).eql( [2,2,1] )
AssertionError: expected Array ...

> should.config.plusZeroAndMinusZeroEqual = true
> should([2,2,0]).eql( [2,2,1] )
Assertion {
  obj: [ 2, 2, 0 ],
  anyOne: false,
  negate: false,
  params: 
   { operator: 'to equal',
     expected: [ 2, 2, 1 ],
     message: undefined,
     details: '',
     showDiff: true } }
```

**Note**: Can I suggest a shorter name for this configuration? maybe this one:
```javascript
should.config.discriminateMinusZero (default true)
```

**Comment by VinGarcia** [comment]
Hi again @btd, I submitted a pull request to `shouldjs/equal` that should fix this bug. I hope it helps.

**Comment by btd** [comment]
@VinGarcia thanks. Merged and published.

**Comment by btd** [comment]
@VinGarcia good now?

**Comment by VinGarcia** [comment]
Yep, it's good! Closing this issue, thank you!
